### ISSUE TITLE
Precompiled Handlebars templating causing performance issues on crappy CMS?

### ISSUE THREAD

**Issue by takes12no1** [bjorn2404/jQuery-Store-Locator-Plugin#102]
I am new to using Github, please forgive if this is the wrong forum for such a request.
This project has been very helpful for me to get a branch locator up quickly. However, I am using this on a CMS that is horrible and does script and code injections for every page served. So When results are templated the performance speed takes a huge hit. I will need to dig in and make a version without templating. Any Resources that anyone could point me to would be much appreciated.

**Comment by bjorn2404** [comment]
I'm assuming you're talking about the Handlebars templates. You might try doing inline templates with the listTemplateID and infowindowTemplateID plugin settings to avoid having the templates in separate files. The second example on the [Handlebars](http://handlebarsjs.com/) site is what a template looks like within a script tag.

**Comment by takes12no1** [comment]
Interesting, so you're saying by compiling the template in the browser (using he script method) instead of pre-compiling it,  I might overcome the issue. Thanks, I will pursue that route. If I discover this helps, is it cool to post the solution here to potentially help someone else? I know the use case is rare but still...

**Comment by bjorn2404** [comment]
Well, you could just try doing the templates with inline JS. If that's still not good enough you could go the compiled route - there's a Grunt task out there for doing that.
