### ISSUE TITLE
Pagination updating error

### ISSUE THREAD

**Issue by rlandeiro** [bjorn2404/jQuery-Store-Locator-Plugin#103]
Noticed a few bugs with the pagination function. You can take a look here: http://bit.ly/1Uebqhk
Using: `'slideMap' : true,
			'locationsPerPage' : 5,
			'pagination': true,
			'originMarker' : true,
			'inlineDirections': true,
			'geocodeID': 'locator',`

#1:
If I search for a zip (10018) the map loads fine with the pagination.
If I click on 2 (pagination), the map loads fine.
Same for 3, 4, 5 in that order.
From page 5 if you click backwards (4,3,2,1), the map load very slowly and refreshes a few times per click. In fact if you keep clicking on different pages, it looks like the map is refreshing even more and getting even slower.

#2 
If I click on Near Me button (geocodeID), the map loads fine with the pagination.
If I click on 2 (pagination), the map and list refreshes with the same top 4 results, changing only the last result. In addition, the distance miles is the same for all the results. Original distance is coming from the last result. Even though I clicked on '2', '1' is still marked and '2' is still clickable.
If I click on 2 (again), the map and list refreshes and the last option on page 1 is now the first option on this page. All the distance miles are still the same, probably from the last result on this page.
If I click on 3, the map and list refreshes and continues the trend from above where the distance miles are all the same.
Same error in this situation as in #1 above where the map refreshes multiple times and gets slower as I click on more pages.

#3 
In this case I added dragSearch:true.
As long as I don't click and drag the map after a search or autolocate, the above two situations still occur.
After either a search or autolocate and I drag the map the results appear fine on the map and list.
But if I click on a pagination number, the map and list refreshes with the same information, never updating.

Let me know if there is anything else you may need to help track down the bug.

**Comment by bjorn2404** [comment]
I was actually already looking into pagination. I think I've fixed the issues on the development branch if you want to download the the latest and try it out https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/tree/development

**Comment by rlandeiro** [comment]
Looks like that update worked with normal search, geocodeID, and the dragSearch.
You can take a look if you'd like: http://bit.ly/1Uebqhk

Thanks!
