### ISSUE TITLE
Options to display a numeric or alpha for results id

### ISSUE THREAD

**Issue by enrmbigg** [bjorn2404/jQuery-Store-Locator-Plugin#107]
For each individual result your display a alpha id and a numeric if its under 25 locations, there should be a option whether or not to override this and by default just pick numeric instead.

**Comment by bjorn2404** [comment]
Yeah, I suppose I could work that in at some point. The easiest route without modifying the plugin would be to just set the limit to 26.

**Comment by bjorn2404** [comment]
Added disableAlphaMarkers setting in v2.6.0
