### ISSUE TITLE
Multiple markers on same address

### ISSUE THREAD

**Issue by cneveu** [bjorn2404/jQuery-Store-Locator-Plugin#110]
When marker pins overlap each other (when they have the same address), it would be nice to have the possibility to display them like this : 
http://jawj.github.io/OverlappingMarkerSpiderfier/demo.html

**Comment by cneveu** [comment]
I'm trying to make jQuery Store Locator and Overlapping Marker Spiderfier working together, but it seems to be not a simple task to complete!

**Comment by bjorn2404** [comment]
Closed as duplicate of https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/issues/33
