### ISSUE TITLE
When 'originMarker' is set to true, the list disappears.

### ISSUE THREAD

**Issue by newersdk** [bjorn2404/jQuery-Store-Locator-Plugin#111]
Hi

When I set 'originMarker' to true on my site, the list of stores disappears and there is no origin marker on the map. 

Can you help with this? 

Thank you!

**Comment by bjorn2404** [comment]
What other options are you using?

**Comment by newersdk** [comment]
'markerImg'                : 'assets/img/park.png',
'markerDim'                : { height: 20, width: 20 },
'catMarkers'               : null,
'selectedMarkerImg'        : null,
'selectedMarkerImgDim'     : null,
'lengthUnit'               : 'km',
'storeLimit'               : 26,
'distanceAlert'            : 60,
'dataType'                 : 'xml',
'dataLocation'             : 'data/locations.xml',
'dataRaw'                  : null,
'xmlElement'               : 'marker',
'listColor1'               : '#ffffff',
'listColor2'               : '#eeeeee',
'originMarker'             : false,
'originMarkerImg'          : null,
'originMarkerDim'          : null,
'bounceMarker'             : true,
'slideMap'                 : true,
'modal'                    : false,
'overlay'                  : 'bh-sl-overlay',
'modalWindow'              : 'bh-sl-modal-window',
'modalContent'             : 'bh-sl-modal-content',
'closeIcon'                : 'bh-sl-close-icon',
'defaultLoc'               : false,
'defaultLat'               : null,
'defaultLng'               : null,
'autoComplete'             : false,
'autoGeocode'              : true,
'geocodeID'                : null,
'maxDistance'              : false,
'maxDistanceID'            : 'bh-sl-maxdistance',
'fullMapStart'             : false,
'fullMapStartBlank'        : false,
'fullMapStartListLimit'    : false,
'noForm'                   : false,
'loading'                  : false,
'loadingContainer'         : 'bh-sl-loading',
'featuredLocations'        : false,
'pagination'               : false,
'locationsPerPage'         : 10,
'inlineDirections'         : true,
'nameSearch'               : false,
'searchID'                 : 'bh-sl-search',
'nameAttribute'            : 'name',
'visibleMarkersList'       : false,
'dragSearch'               : false,
'infowindowTemplatePath'   :
'assets/js/plugins/storeLocator/templates/infowindow-description.html',
'listTemplatePath'         :
'assets/js/plugins/storeLocator/templates/location-list-description.html',
'KMLinfowindowTemplatePath':
'assets/js/plugins/storeLocator/templates/kml-infowindow-description.html',
'KMLlistTemplatePath'      :
'assets/js/plugins/storeLocator/templates/kml-location-list-description.html',
'listTemplateID'           : null,
'infowindowTemplateID'     : null,
'taxonomyFilters'          : null,
'taxonomyFiltersContainer' : 'bh-sl-filters-container',
'exclusiveFiltering'       : false,
'querystringParams'        : false,
'debug'                    : false,
'sessionStorage'           : false,
'callbackNotify'           : null,
'callbackBeforeSend'       : null,
'callbackSuccess'          : null,
'callbackModalOpen'        : null,
'callbackModalReady'       : null,
'callbackModalClose'       : null,
'callbackJsonp'            : null,
'callbackPageChange'       : null,
'callbackDirectionsRequest': null,
'callbackCloseDirections'  : null,
'callbackNoResults'        : null,
'callbackListClick'        : null,
'callbackMarkerClick'      : null,
'callbackFilters'          : null,
// Language options
'addressErrorAlert'        : 'Adresse ikke fundet.',
'autoGeocodeErrorAlert'    : 'Automatisk adresse ikke fundet, venligst tast
sted eller adresse.',
'distanceErrorAlert'       : 'Desværre er den tætteste parkering over  ',
'mileLang'                 : 'mile',
'milesLang'                : 'miles',
'kilometerLang'            : 'kilometer',
'kilometersLang'           : 'kilometre',
'noResultsTitle'           : 'Ingen resultater',
'noResultsDesc'            : 'Ingen adresser fundet, venligst omskriv.',
'nextPage'                 : 'Næste &raquo;',
'prevPage'                 : '&laquo; Forrige'

**Comment by bjorn2404** [comment]
This issue is fixed in v2.6.0
