### ISSUE TITLE
Addition of new handlebars filters

### ISSUE THREAD

**Issue by christianrochford** [bjorn2404/jQuery-Store-Locator-Plugin#112]
More of a request than an issue. I need to create a nested json object within my locations file, however, the twig used within the project doesn't seem to allow for looping through a json array, e.g. 
```
{% for category in categories %}
<a href="/category/{{ category.id }}" class="icon-{{ category.name }}"></a>
{% endfor %}
```
I'm quite new to twig so am not sure how this may be achieved. I've created my nested json object but have no way to output the data. I've found this option http://stackoverflow.com/questions/11841515/twig-iterate-over-object-properties but am not sure how to get the twig filter in place to allow for looping through the data.
Thanks a lot!

**Comment by bjorn2404** [comment]
I'm not sure if I'm interpreting correctly but this seems like more of a twig question. I'm not familiar with twig.

**Comment by christianrochford** [comment]
Yep its twig question related to the following file:
https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/dist/assets/js/plugins/storeLocator/templates/location-list-description.html
I'm trying to loop through a nested json object within this template

**Comment by bjorn2404** [comment]
Ah, ok you'll probably want to look at the each block helper: http://handlebarsjs.com/builtin_helpers.html#iteration

**Comment by christianrochford** [comment]
Perfect, I've got that working now, thanks!
