### ISSUE TITLE
Searching geographic boundries

### ISSUE THREAD

**Issue by rlandeiro** [bjorn2404/jQuery-Store-Locator-Plugin#113]
Currently, the plugin adds a query string to the genxml.php file that includes orginLat and orginLng.
`phpsqlsearch_genxml.php?origLat=27.6648274&origLng=-81.51575350000002&origAddress=florida`.
And these come from the GeocodeService.Search file that has the "location" lat and lng values.
`"location" : {
               "lat" : 27.6648274,
               "lng" : -81.5157535
            },`

Although this works great when you geocode "Jacksonville, FL", it does not work well when you try to geocode "Florida" since that results in the lat/lng for the center of the state. And if there is a max distance, then you may not see Jacksonville as a result.

It would be great to have the option to search within the geographic boundaries as well (since they are provided in the Geocode.Service.Search file anyway) so you can capture the entire state.
`"bounds" : {
               "northeast" : {
                  "lat" : 31.000968,
                  "lng" : -80.0311371
               },
               "southwest" : {
                  "lat" : 24.5210795,
                  "lng" : -87.634896
               }
            },`

If the boundaries can be added to the query string, then a script can be added to search boundaries if no results were found with the single location. 

Example:
`phpsqlsearch_genxml.php?origLat=27.6648274&origLng=-81.51575350000002&neLat=31.000968&nelng=-80.0311371&swLat=24.5210795&swLng=-87.634896&origAddress=florida`.

I currently find the close locations with the following PHP calculation (wp_ being the store coordinates) :
`$near_locations =(3959 * acos( cos( deg2rad($origLat) ) * cos( deg2rad( $wp_lat ) ) * cos( deg2rad( $wp_lng ) - deg2rad($origLng) ) + sin( deg2rad($origLat) ) * sin( deg2rad( $wp_lat ) ) ) );`

With the new query string suggested, if the result were to be zero for my calculation, then I would run a new calculation that would search inside the boundaries.

**Comment by bjorn2404** [comment]
Interesting. Yeah I can output that information as well in the AJAX request. I may also work the formula into the plugin somehow.

**Comment by bjorn2404** [comment]
v2.6.0 now passes boundsNorthEast, boundsSouthWest and formattedAddress with the AJAX request
