### ISSUE TITLE
Form submission

### ISSUE THREAD

**Issue by Redani** [bjorn2404/jQuery-Store-Locator-Plugin#116]
Hej Bjorn, hope you're doing well and thanks for this new update which is really full and packed of options and callbacks functions :)

I'm trying to implement it but i'm facing a little small problem: in all your example you always submit the variables 'origLat', 'origLng' and 'origAddress'. In my case I will not need these 3 variables but rather a custom ones that i include in the form: 'zip' and 'country'. And I don't really need to use the geocode function.

I had to tweak your code by replace this:
`data: {
	'origLat' : lat,
	'origLng' : lng,
	'origAddress': address
}`
with
`data: $("#bh-sl-user-location").serialize()`

But i was wondering if it's possible to do so without altering your code.

Thanks a lot and have a great sunday

**Comment by bjorn2404** [comment]
I don't have a way for passing custom things at this point so you'd want to add what you need in that AJAX call. However, you could use the origLat/origLng coordinates and do a reverse geocode on them to get the information that you need instead of trying to pass it over.

**Comment by Redani** [comment]
Thanks for your reply!
Actually I can not use origLat/origLng because only the zip code is required to retrieve the locations... :(

1- is it possible to deactivate the generation of origLat/origLng? maybe the plugin will run a little faster?

2- I'm displaying the map in an overlay with another form to search again by zip code. As you are using ID for the form and the input search, I think I must have another form with other IDs ("bh-sl-user-location2" and "bh-sl-address2") and of course changing "formID" and "addressID". I'm currently struggling to run 2 instances of store locator. How can I do that? or what is the best way to have 2 search forms ?

3- for better styling the map, I have set the locations list as absolute position. When I click on the list, the infowindow is kindda centered in the map, but when i click on a marker which is near the list, the infowindow is hidden and doens't center... :( is there a fix for this?

Thanks a lot
Cheers

<img width="1325" alt="screen shot 2016-05-31 at 10 49 31" src="https://cloud.githubusercontent.com/assets/328526/15670467/886ac174-271d-11e6-9bcb-4e7694be26ef.png">

**Comment by Redani** [comment]
Hi again,
I know that you don't have to answer all questions and you're just doing favors by providing support. But I just would like pls to know if they are easy solutions for my questions 2 & 3, or if I should find some twaeks in js... Thanks a lot :)

**Comment by bjorn2404** [comment]
1. It is not possible to deactivate origLat/origLng
2. The plugin is not set up to be able to run more than once on the same page
3. Don't use absolute positioning if having the list over the map is going to be a concern

**Comment by Redani** [comment]
Thanks for your reply.

2- so what would be the best way to have the search form in the main page and also in the overlay?

**Comment by Redani** [comment]
Hi, again I feel embarrassed to chase you up :/ I'm really stuck and can't move on, could you please just tell me if there is a fix for the question 4, it's the most important one.
thank you

**Comment by bjorn2404** [comment]
How are you pre-filling in the input field? Maybe use a placeholder instead?

**Comment by Redani** [comment]
I'm pre-filling the inout using `value="<?php echo $value; ?>"`
Cool, i didn't know that it already prefills the input, thanks :)
