### ISSUE TITLE
Category taxonomy filter not working using query string

### ISSUE THREAD

**Issue by thedesigncore** [bjorn2404/jQuery-Store-Locator-Plugin#117]
I have taxonomyFilters set up using categories and it is working correctly using a search form on the same page as the map.

But if I move the search form to a different page other than the map and use the query string to submit the form, the address part of the search works fine but the the category filter is ignored.

My query string looks like this: ?locator-max-distance=100&locator-address=austin&category=Industrial&submit=submit

locator-max-distance works & locator-address works, just not category.

**Comment by bjorn2404** [comment]
The plugin is not currently set up to handle category query string parameters.

**Comment by thedesigncore** [comment]
Any chance of this feature being added?

**Comment by bjorn2404** [comment]
I'll be adding this within the next two months.

**Comment by bjorn2404** [comment]
This functionality has been added to v2.7.0.
