### ISSUE TITLE
letterMarkerImg to be part of the settings?

### ISSUE THREAD

**Issue by paul-blundell** [bjorn2404/jQuery-Store-Locator-Plugin#120]
There is a URL assigned to the variable letterMarkerImg and this loads a Google waypoint marker with a customised letter. It would be very useful if we could set that URL as part of the plugins settings.

For example, I have created my own address that will render my icon with the letter provided but I have had to change this URL directly in the plugin code.

Thanks.

**Comment by bjorn2404** [comment]
What does your URL end up looking like? Do you still use all the query string parameters?

**Comment by paul-blundell** [comment]
It looks something like: http://mysite.com/stores/marker/letter/D

In my case, no, I only use the letter. But I guess others might still want to specify other params or even just edit the params from the google waypoint URL.

**Comment by bjorn2404** [comment]
I took a look at this again and remembered the reason why I have it hardcoded. When using the default markers with the label parameter the marker animation, which I have set to true by default, only moves the marker icon and not the label. It was accepted by Google as a bug about a year ago but not sure if it will ever be addressed:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=8573

So, not sure if I should remove the marker animation or wait for Google to fix.

**Comment by bjorn2404** [comment]
I've added a new callbackCreateMarker callback in v2.7.0 that can be used to override the markers. It seemed like this was the best way vs. adding another setting. More info can be found in the new callback documentation: https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks.md
