### ISSUE TITLE
instead of searching stores in 60  kilometers radius

### ISSUE THREAD

**Issue by soori007** [bjorn2404/jQuery-Store-Locator-Plugin#123]
instead of searching stores in 60  kilometers radius is their any option with google auto complete and zoom in to seleted location instead sending request to google

**Comment by bjorn2404** [comment]
The purpose of this plugin is to be a locator of locations from an origin point. You could certainly set up a custom script to map a point on a map with the HTML5 Geolocation API but what you're describing seems different from the purpose of this plugin.
