### ISSUE TITLE
Boundary search with query search

### ISSUE THREAD

**Issue by rlandeiro** [bjorn2404/jQuery-Store-Locator-Plugin#127]
I noticed that if you search for a generic area (ex: city area), the boundary search works great, and gets populated in the GeocodeService.Search file. 
But if you search for a specific perfect address, the file does not provide any boundaries, which breaks the search in a console error:
`jquery.storelocator.js:446 Uncaught TypeError: Cannot read property 'getNorthEast' of undefined`

You can recreate this by going to your example page: https://bjornblog.com/storelocator/v2/query-string-example/submit.html?bh-sl-address=6801+York+Avenue+South+Edina%2C+MN+55435

**Comment by bjorn2404** [comment]
Thanks, I will get that fixed in the next couple of days.

**Comment by bjorn2404** [comment]
Fixed in v2.6.1
