### ISSUE TITLE
Rebuild map  with new locations 

### ISSUE THREAD

**Issue by pathprabu** [bjorn2404/jQuery-Store-Locator-Plugin#128]
I am trying to rebuild map with new locations...If i  try destroy()  entire container gone and map not loading...Could you guide me how to rebuild with new locations....?

**Comment by bjorn2404** [comment]
You probably just want to run reset first instead of destroy and then either process the form again or run the main mapping method.

**Comment by cosmointeractive** [comment]
What's the syntax to call the reset method?

**Comment by cosmointeractive** [comment]
Never mind. For anyone else who is looking to know as well... I wanted to call the destroy method. I can do so by doing this `$('#bh-sl-map-container').storeLocator('destroy');`

**Comment by dhruvangg** [comment]
After destroyed, it won't take new locations from the JSON array. It reinitialized by old data.
