### ISSUE TITLE
"Unable to find address" error

### ISSUE THREAD

**Issue by cosmointeractive** [bjorn2404/jQuery-Store-Locator-Plugin#132]
When I run the bootstrap example in WAMP I receive the following error `Unable to find address` when I perform a search for zipcode. And this `Error: Geocode was not successful for the following reason: REQUEST_DENIED` appears in Firefox/Firebug. This issue happened after I resolved an issue where the template files would not load. Same issue as #76 apparently.

**Comment by bjorn2404** [comment]
Google Maps is now requiring an API key for all new URLs. [Create one](https://developers.google.com/maps/documentation/javascript/get-api-key#key), follow the instructions on that page and make sure to enable Google Places API Web Service, Google Maps Geocoding API and Google Maps Directions API for the project in the Google API Console after setting up the initial Maps key.
