### ISSUE TITLE
running in liferay as a portlet ?

### ISSUE THREAD

**Issue by pranireddy9** [bjorn2404/jQuery-Store-Locator-Plugin#133]
Hi , 

Do you have any idea how to run this app as web app in liferay portal as a portlet ? or atleast running in the web container ?

Thanks,
Pranitha.

**Comment by areddy7021** [comment]
Hi ,

As i am facing the same issue while working with the example files. Please help me out in fixing this.

Error: Could not load plugin templates. Check the paths and ensure they have been uploaded. Paths will be wrong if you do not run this from a web server.

Thanks,
Akhil.

**Comment by bjorn2404** [comment]
Sorry, I'm not familiar with Liferay. The plugin structure is based on the "lightweight" boilerplate programming pattern so I would hope that any information out there about getting a jQuery plugin to work with Liferay might work with this plugin as well.

**Comment by pranireddy9** [comment]
Thank you bjorn , do you have any idea in deploying this whole example in tomcat container as i am doing in my local with the grunt and with this command http-server -c-1. SO my question is i would like to run the same way what i am running with the npm to run in the tomcat as a war and the same war which i can deploy in the liferay. In liferay i have written a portlet where i have written jsps and and included your js files . I am not able to load the map functionality since you are executing some scripts while loading through grunt or javascript. I have to accomplish the same task in the tomcat. Can you please point to me if you have some thing ..i am just confused with this stuff how i can run your project in tomcat ?

**Comment by pranireddy9** [comment]
no issues , i figured out thank you very much for  your plugin and i have a quick question do we get any manger images for the store on the map , do i need to do any changes for that to display branch manager jpeg files along with the address ?

**Comment by bjorn2404** [comment]
Add an attribute to your location data with the full URL to the image. Then in the [Handlebars template](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/tree/master/dist/assets/js/plugins/storeLocator/templates) just call that attribute in an image source value. Such as:

`<img src="{{locationImg}}">`
