### ISSUE TITLE
store-locator/argument is failing

### ISSUE THREAD

**Issue by kirantej** [bjorn2404/jQuery-Store-Locator-Plugin#134]
Hi,

We created a page for the store locator as store-locator. But, when we try to pass any arguments as store-locator/argument, the store locator page is failing, It is loading the list-display with the store-locator page and its looping multiple times.

Is there a way to resolve this issue?

**Comment by bjorn2404** [comment]
You are using the querystringParams option?

**Comment by kirantej** [comment]
We enabled that option as 'True'. But, when users tried with store-locator/test, the list template is loading multiple times.

**Comment by bjorn2404** [comment]
You need the query string parameter for this to work: bh-sl-address= I'm not sure why you'd think it would work with just a parameter. Also, don't include the jQuery plugin call on the page with the initial submit form. See the query string example files:

https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/tree/master/dist/query-string-example

**Comment by kirantej** [comment]
Ok. Thank you.
