### ISSUE TITLE
Not showing current location and stores if i change the distance limit ?

### ISSUE THREAD

**Issue by pranireddy9** [bjorn2404/jQuery-Store-Locator-Plugin#136]
Hi , 

I was able to pull out the locations if i keep my distance limit with in 10 miles and it showing up in the map with the locations and giving me the alert window and then loading is fine. But when i have tried increased the distance limit then obviously it is not giving any popup since some of the locations are there with in that distance range but the interesting part is those locations are not getting displayed and even user location is also not getting displayed . is popup is associated with  those location icons on map or is it something different ?

It looks like this , its displaying the locations at side but not on the map.

![image](https://cloud.githubusercontent.com/assets/19625325/16933090/6b7e11d8-4d10-11e6-919d-b384ada9d7e9.png)

Thanks,
Pranitha.

**Comment by bjorn2404** [comment]
The nearest location appears to be 26 miles away. You might try changing in the initial zoom if your locations are spread out.
