### ISSUE TITLE
no rendering on ipad

### ISSUE THREAD

**Issue by slepit** [bjorn2404/jQuery-Store-Locator-Plugin#140]
Hi,

great library.
FYI, it displays correctly on a desktop browser, but does not seam to work on iPad and iPhone.
The search after the submit button click runs forever.

The OS is iOS 9.

**Comment by bjorn2404** [comment]
I've had some reports of issues with mobile Safari but haven't been able to replicate the issue. Try using inline templates to see if that fixes the problem:

https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/issues/76
