### ISSUE TITLE
Issue resolving post code 2000

### ISSUE THREAD

**Issue by ghettoboombox** [bjorn2404/jQuery-Store-Locator-Plugin#141]
Found a bug when using the store locator with XML and trying to enter the post code for 2000. I can enter the suburb name of "Sydney" and it finds matches for stores close to the region. and if i enter postcode 3000 for Melbourne it works also. When entering 2000 it cant find any results even when I move the results to the top of the XML file, it continues to fail

**Comment by bjorn2404** [comment]
Are all the locations in Australia? If so, have you tried using region biasing as outlined in the documentation?
