### ISSUE TITLE
How to reset search query on click

### ISSUE THREAD

**Issue by chiraggmodi** [bjorn2404/jQuery-Store-Locator-Plugin#145]
Hi,
I want to reset search query when clicked on button.
Can you please guide me how can i reset map location when clicked.

What i am doing is,
i have make list of Country and when any once click on that country it shows that country list, but when some one search from search box and if that location is not found there is no way to go back to the list. So i want location to get reset when click on any country list.

**Comment by bjorn2404** [comment]
I'm working on this. Should be available in the next version.

**Comment by chiraggmodi** [comment]
no issue, actually i have figured out this by my self.. but if will be nice to have this in core plugin... any ways can ETA for release?

**Comment by bjorn2404** [comment]
Probably within the next 2 weeks.

**Comment by bjorn2404** [comment]
Reset functionality has been added with v2.7.0. Add an HTML element with the class "bh-sl-reset" to trigger it.

**Comment by chiraggmodi** [comment]
thank man!!

**Comment by rriky92** [comment]
Not working with this settings: 'fullMapStart': true,
					'distanceAlert': -1,
					'storeLimit' : -1,
					'visibleMarkersList' :true,
