### ISSUE TITLE
Use with live data

### ISSUE THREAD

**Issue by slepit** [bjorn2404/jQuery-Store-Locator-Plugin#147]
Hi,

great library.

Is it possible to use your library with data extracted on the fly from a database ? 
I have seen that it is possible to do that by extracting the data to a JSON file on disk, but would that be possible to directly pass the data in JSON format to the constructor ?

Is it possible also to change the text that is displayed in the sidebar and/or in the tooltip window ?

thanks

**Comment by bjorn2404** [comment]
Yes, you can use the information outlined in this post even though you might not be using that many locations:

http://www.bjornblog.com/web/using-the-jquery-store-locator-with-thousands-of-locations

Location List and Infowindows can be changed with the Handlebars templates.
