### ISSUE TITLE
Use Twig instead of handlebar ?

### ISSUE THREAD

**Issue by odecharette** [bjorn2404/jQuery-Store-Locator-Plugin#148]
Hi

Great plugin !! thanks !

Would it be possible to use TWIG for templates instead of handlebar ?

For location-list-description and infowindow-description files ?

Olivia

**Comment by bjorn2404** [comment]
No, Handlebars is pretty integrated into the plugin and Twig is a PHP templating engine. This is a JavaScript/jQuery project.
