### ISSUE TITLE
Using with Magento 2.1

### ISSUE THREAD

**Issue by Flicker17** [bjorn2404/jQuery-Store-Locator-Plugin#153]
I'm trying to set this up with Magento 2.1. I have this working on a simple sandbox folder on my local machine, but bring these same files into my Magento theme and it's not rendering. All of the linked css/js files, etc, are there, but again nothing comes up. Can you just take a quick look at the link, and see if you see anything wrong?

http://dev.gronomics.com/retailers

**Comment by bjorn2404** [comment]
I'd start by wrapping your jQuery in noConflict. I'm seeing "$ is not a function" errors.

```javascript
jQuery.noConflict();
(function( $ ) {
	$(document).ready(function() {
		
		$('#bh-sl-map-container').storeLocator({
			'fullMapStart'				: true,
			'dataLocation'				: 'http://dev.gronomics.com/pub/static/frontend/Gronomics/evolve/en_US/retailers/gronomics-retailers.xml',
			'infowindowTemplatePath'	: 'http://dev.gronomics.com/pub/static/frontend/Gronomics/evolve/en_US/retailers/assets/js/templates/infowindow-description.html',
			'listTemplatePath'			: 'http://dev.gronomics.com/pub/static/frontend/Gronomics/evolve/en_US/retailers/assets/js/templates/location-list-description.html',
			'KMLinfowindowTemplatePath'	: 'http://dev.gronomics.com/pub/static/frontend/Gronomics/evolve/en_US/retailers/assets/js/templates/kml-infowindow-description.html',
			'KMLlistTemplatePath'		: 'http://dev.gronomics.com/pub/static/frontend/Gronomics/evolve/en_US/retailers/assets/js/templates/kml-location-list-description.html'
		});
		
	});
})(jQuery);
```

**Comment by Flicker17** [comment]
Thank you, Bjorn.

Curious, for other projects, do you ever freelance? I work out of Rogers, MN, and sometimes need help with projects - I work mostly with WordPress.


Thanks,

Brent Mattson, President
Flicker Creative Inc
Inspired Designs • Solid Development • Happy Clients

P: 612-315-5369
C: 952-484-0443
Email: brent@flickercreative.com <mailto:brent@flickercreative.com>
Web: flickercreative.com <http://flickercreative.com/>
Office: Minnesota
