### ISSUE TITLE
custom sort by filters. like by date by id of location 

### ISSUE THREAD

**Issue by soori007** [bjorn2404/jQuery-Store-Locator-Plugin#155]
on issue number  #154.

we have taxonomy filters will work based on regex. I want filter like sort by date sort by alphabet kind.
how can i do that. if i use taxonomy filter it will match with json data. how can i achieve this.

any help would be appreciated .

**Comment by soori007** [comment]
And I dont want map to be reloaded again. Just right side template should be filtered(updated)

**Comment by bjorn2404** [comment]
This would involve quite a bit of custom work. I would recommend hiring a developer.
