### ISSUE TITLE
Searching by name after searching by address does not clear origin

### ISSUE THREAD

**Issue by craigpestell** [bjorn2404/jQuery-Store-Locator-Plugin#160]
When using the search by name feature, if I first search by address, then by name, the map stays on the last address location and does not show all the stores by name.

I fixed this by adding `mappingObj.origin = undefined;` to the last section of processForm function, in the `else if(searchInput !== '') {` case.

**Comment by bjorn2404** [comment]
Thanks, fixed in v2.7.2
