### ISSUE TITLE
Add option/callback to modify address before geocoding

### ISSUE THREAD

**Issue by wilsonwc** [bjorn2404/jQuery-Store-Locator-Plugin#161]
I have found that it is necessary to append the country in some instances, especially when searching with just a post code (geocoding "2000" doesn't work, but "2000 Australia" does).  Just thinking that we could have an option or a callback function that would process the address before it is sent to the geocoding service.

**Comment by bjorn2404** [comment]
Sure, that seems pretty easy to add. It's in v2.7.2 with [callbackRegion](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks/callback-region.md). You can also add a region select field for users to pick their region with the existing regionID setting.
