### ISSUE TITLE
Set initial zoom and zoom in on after selecting from autoComplete

### ISSUE THREAD

**Issue by heyjul3s** [bjorn2404/jQuery-Store-Locator-Plugin#162]
Hi,

So I've a maps going on with locations read in from an xml. I was just wondering if it's possible to set a zoom initially when the map loads that shows the whole country and upon after when I select a location from the autoComplete, it zooms in into that particular target location?

Thanks.

**Comment by bjorn2404** [comment]
@heyjul3s If you set the fullMapStart option to true it should work exactly how you are describing.
