### ISSUE TITLE
callbackCreateMarker incorrect letter when showing more than 26

### ISSUE THREAD

**Issue by paul-blundell** [bjorn2404/jQuery-Store-Locator-Plugin#168]
If we have more than 26 locations being shown the results list correctly changes the marker so it uses numbers instead of letters but this is not the case in the map itself, which remains as letters.

We are using the callbackCreateMarker function to define the marker and the letter parameter.

Is there a way to force numbers instead of letters?

**Comment by bjorn2404** [comment]
@paul-blundell Did you try the disableAlphaMarkers setting?
