### ISSUE TITLE
Destroy function

### ISSUE THREAD

**Issue by ChristianGrieger** [bjorn2404/jQuery-Store-Locator-Plugin#170]
Hello,

i just found the reset function that can be triggered with the class"bh-sl-reset".

Is there a way to delete the generated map and results? I would love to give the option to close the map after its loaded.

Greetings,
Chris

**Comment by bjorn2404** [comment]
@ChristianGrieger destroy is a public method:

```javascript
$('#bh-sl-test').on('click', function(e) {
	e.preventDefault();

	$('#bh-sl-map-container').storeLocator( 'destroy' );
});
```
