### ISSUE TITLE
catMarkers and taxonomyFilters fail when used in combination

### ISSUE THREAD

**Issue by avtec** [bjorn2404/jQuery-Store-Locator-Plugin#172]
Hi Bjorn,
I love the locator you've created and I thank you for your work. 
I noticed that when you combine catMarkers and taxonomyFilters, they do not play nicely together and causes the map to disappear. Ideally, these options should go hand in hand. When you select one or two categories you see them listed, distinguished by different markers.

The problem could be my coding, but it seems like it might be a bug.
Have you found this to be true?

`<script>
			$(function() {
				$('#bh-sl-map-container').storeLocator({
					'slideMap' : false,
					'autoGeocode': false,
					'inlineDirections': true,
					'defaultLoc': true,
					'maxDistance': false,
					'modal': false,
					'fullMapStart': true,
					'featuredLocations': false,
					'loading': true,
					'defaultLat': '41.123737',
					'defaultLng' : '-85.125106',
 					'dataType': 'json',
					'dataLocation': 'data/locations.json',
					'originMarker': false,
					'distanceAlert': -1,
					'dragSearch' : false,
					'nameSearch': true,		
					'bounceMarker': true,
					'taxonomyFilters' : {
						'category': 'category-filters-container1',
						'features': 'category-filters-container2',
						'city': 'city-filter',
						'postal': 'postal-filter',
					'catMarkers' : {
					'branch' : ['assets/img/blue-marker.png', 32, 32],
					'atm' : ['assets/img/red-marker.png', 32, 32],
					}
				});
			});
		</script>`

thanks for your time,
Rye

**Comment by bjorn2404** [comment]
@avtec They work fine in combination. You've got the catMarkers setting within the taxonomyFilters value object. They are separate settings - check the bracket placement:

```javascript
		'taxonomyFilters' : {
			'category': 'category-filters-container1',
			'features': 'category-filters-container2',
			'city': 'city-filter',
			'postal': 'postal-filter'
		},
		'catMarkers' : {
			'branch' : ['assets/img/blue-marker.png', 32, 32],
			'atm' : ['assets/img/red-marker.png', 32, 32]
		}
	});
);
```

**Comment by avtec** [comment]
Thanks @bjorn2404 ! Works perfectly now.
