### ISSUE TITLE
No results handling

### ISSUE THREAD

**Issue by Redani** [bjorn2404/jQuery-Store-Locator-Plugin#173]
Hi Bjorn and thanks a lot for the amazing work you've been achieving so far.

I have a special case that I would like to use and don't know if it's managed by the plugin.
I see you have "noResultsTitle" which is used when not geolocation was found, but in my case, i would like to display a message when the locations resutls returns no resutls, (only the tag "markers"), is that possible?

thanks in advance
Cheers

**Comment by Redani** [comment]
awtch, just noticed the calback function: callbackNoResults, sorry :/

**Comment by bjorn2404** [comment]
@Redani No, the plugin is not able to do multiple instances on the same page.

**Comment by Redani** [comment]
OK, thanks :)
Any plans to add this possibility?

**Comment by bjorn2404** [comment]
Sorry, not at this time.
