### ISSUE TITLE
dragSearch "map is undefined" error

### ISSUE THREAD

**Issue by LaurenceHA** [bjorn2404/jQuery-Store-Locator-Plugin#175]
Hi,

I'm attempting to use the dragSearch option but every time I drag the map and the function is called, an error is thrown. It simply says that "map in undefined". 

Here is the code I am using:

			$(function() {
				$('#bh-sl-map-container').storeLocator({
					'dataType': 'json',
					'dataLocation': 'data/populate.php',
					'defaultLoc': true,
					'defaultLat': '',
					'defaultLng' : '',
					'autoComplete': true,
					'storeLimit' : 30,
					'dragSearch' : true	
				});
			});

Obviously the, latitude and longitude would be filled in. So I'm wondering if you have any advice to help me with this!

Thanks,

Laurence

**Comment by bjorn2404** [comment]
@LaurenceHA Thanks, yes it appears dragSearch was broken after merging 45cb909. I'm still working on a few things for the next version but I've pushed an update to the [development branch](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/tree/development) with a fix.

**Comment by bjorn2404** [comment]
@LaurenceHA I've just pushed up v2.7.3, which includes the fix for this issue.
