### ISSUE TITLE
Map coordinates doesn't match with Google Maps

### ISSUE THREAD

**Issue by rriky92** [bjorn2404/jQuery-Store-Locator-Plugin#177]
When I need coordinates I open google maps, then search for my location and when I want to export it as a link I can find coordinates, but If I set that coordinates in this plugin the final location is different as you can see in screenshot ( look at "La Bifora" & the sea as a reference for the marker point)
![schermata 2017-05-16 alle 18 29 45](https://cloud.githubusercontent.com/assets/270771/26117266/3fbb70a6-3a66-11e7-9573-61b3bb6285cc.png)
![schermata 2017-05-16 alle 18 30 51](https://cloud.githubusercontent.com/assets/270771/26117267/3fe40084-3a66-11e7-97c4-a6451d3c808c.png)
![schermata 2017-05-16 alle 18 31 01](https://cloud.githubusercontent.com/assets/270771/26117268/3ff87820-3a66-11e7-958b-b1a54233fa67.png)

**Comment by bjorn2404** [comment]
@rriky92 The longitude in your example is not as precise as the data that's returned from the Goole Maps Geocoding API. I'd recommend just loading the address in the URL with your Maps API key to get the coordinates instead. I'm using the Google Maps API for everything, so there's no reason it would be different from the data the API returns.

https://developers.google.com/maps/documentation/geocoding/intro#GeocodingResponses
