### ISSUE TITLE
taxonomy filtering no longer works when the data is a number

### ISSUE THREAD

**Issue by PaladinMattt** [bjorn2404/jQuery-Store-Locator-Plugin#178]
the filterData functions throws an error is the data[k] or filter[k] is of type number.

**Comment by bjorn2404** [comment]
@PaladinMattt Just pushed out v2.7.4 with some updates to filtering. I tested numbers and they seemed to be working with this code. Let me know if you're still experiencing issues with it.

**Comment by cameroncollector** [comment]
I'm running into the same issue, currently using v3.0.1. Oddly enough if I use a number with a decimal (ex 8 vs 8.0) it filters fine.
