### ISSUE TITLE
Issue where Map shows only sometimes

### ISSUE THREAD

**Issue by gingermamba32** [bjorn2404/jQuery-Store-Locator-Plugin#179]
Hello Bjorn,

Thanks for the plugin.....it looks and feels great.

I had a quick issue with my page here: http://www.babelash.com/index.php?p=stores

Please try to clear cache, use incognito, etc. and you will see the app only works sometimes. Other times there is just a blank screen and the search button will not work, also bringing the error: Uncaught TypeError: $(...).storeLocator is not a function

I have no idea why, but is there anything you can do to help?

Thanks,

Michael

**Comment by bjorn2404** [comment]
@gingermamba32 You're loading 2 different versions of jQuery:

content/vendors/jquery/jquery-1.9.1.min.js?3715r2=1
