### ISSUE TITLE
Add parameter to filter the list of the stores based on marker visibility

### ISSUE THREAD

**Issue by jacquesletesson** [bjorn2404/jQuery-Store-Locator-Plugin#18]
Hi @bjorn2404 

I added a new parameter to only display on the list the store of which the marker is visible on the map.

If you think there is a better way to do this, let me know.

Hope it helps other.

Cheers,

https://github.com/jacquesletesson/jQuery-Store-Locator-Plugin/commit/2e707fe5cb32e8081542066818604f3c7a35feb3

**Comment by angeenes** [comment]
Hi, how can I use this parameter ?

**Comment by bjorn2404** [comment]
Added in v2.0.6 with visibleMarkersList option.
