### ISSUE TITLE
storeLocator is not a function

### ISSUE THREAD

**Issue by mayankkushal** [bjorn2404/jQuery-Store-Locator-Plugin#180]
Hi, Wonderful work on the plugin. I tried implementing it in my project but I m getting "storeLocator is not a function" error.
I have done exactly like the example. Any suggestion would be wonderful.
Thank you

**Comment by bjorn2404** [comment]
This is usually due to:

- Duplicate jQuery includes
- An improper script path
- Not using $(document).ready (shorthand method is used in all the examples)
