### ISSUE TITLE
Update handlebar templates

### ISSUE THREAD

**Issue by webfolkcreative** [bjorn2404/jQuery-Store-Locator-Plugin#183]
Update handlebar templates with conditionals, in case the information (like phone, web, etc) isn't applicable. This way only the applicable information and markup is outputted.

`{{#if web}}<div><a href="{{web}}" target="_blank">{{niceURL web}}</a></div>{{/if}}`

**Comment by bjorn2404** [comment]
Added extra conditionals to the templates in v3.0.0
