### ISSUE TITLE
Zip code and addresses sometimes are confused

### ISSUE THREAD

**Issue by martinrios95** [bjorn2404/jQuery-Store-Locator-Plugin#184]
Referencing #166 from @manucnx
**Issue**

Hi Bjorn,

I'm Martin from Bahia Blanca, Argentina.

I wanted to use zip codes to locate some stores in my city, but it located an address on the United States.

For example:

Monte Hermoso City is 62 miles from Bahia Blanca, and the zip-code is BA8153.
If I put that on the zip-code/address form, it marks me an address from Tysons, USA.

¿Is it possible to difference the address and the zip-code better?

**Technical Details**

- Using CodeIgniter 3.1.5 on AppServ 8.4.0 on Windows 10 Professional.
- My location is Bahia Blanca, Buenos Aires province (state), Argentina.
- Location after zip-code search from Monte Hermoso (BA8153, 62 miles from Bahia Blanca): 
-> 8153 VA-7, Tysons, VA 22182
-> Montevideo 340, Bahía Blanca, BA 8000

Best regards,

Martin

**Comment by bjorn2404** [comment]
This should be improved with the [component restriction](https://developers.google.com/maps/documentation/javascript/examples/geocoding-component-restriction) addition in v3.0.0 that can work with the existing region functionality.
