### ISSUE TITLE
css-margin between infowindow-description.html and outer GoogleMaps box/border?

### ISSUE THREAD

**Issue by st2xo** [bjorn2404/jQuery-Store-Locator-Plugin#186]
Hi there, 
is there a way to get rid of the margin between the red line and grey line?
All css in ~/js/plugins/storeLocator/templates/infowindow-description.html ends at the red line. 
I want to insert a background-image until the grey border.  Is there a way at all? Thank you.

![openstorelocator](https://user-images.githubusercontent.com/19145522/28609899-b6510b74-71e6-11e7-8517-6df47c3e6eae.png)

**Comment by bjorn2404** [comment]
Styling for the infowindows is pretty limited with the Google Maps API. The plugin is compatible with  the InfoBubble library if you want more control: https://github.com/googlemaps/js-info-bubble and there is an example of how to set it up in the dist folder: https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/dist/infobubble-example.html
