### ISSUE TITLE
Win 10 / IE 11 breaks with JSON or XML after 544 records

### ISSUE THREAD

**Issue by jmp100** [bjorn2404/jQuery-Store-Locator-Plugin#189]
Doesn't work with json data, by address or zipcode. No issues with any other browser.

**Comment by jmp100** [comment]
I believe it's the data. 700 records probably a character breaking the process for IE.

**Comment by jmp100** [comment]
I validated the json @ JSONLint. No issues with data. IE breaks at about record 544. With either real time php json data or static json file.

Any help on this appreciated. 
James

**Comment by jmp100** [comment]
I changed the data type to xml. Scripted out the location data. Same issue with IE 11 and earlier browser versions.  Breaks after 544 records.

**Comment by jmp100** [comment]
No problems with data. I scripted out using the xml schema replacing the name, lon and lat fields with real data. Same issue IE, breaks after 544 records. 

<markers>
	<marker name="3C" lat="39.4900220000" lng="-83.6502520000" category="Restaurant" address="3040 Excelsior Blvd" address2="" city="Minneapolis" state="MN" postal="55416" country="US" phone="612-922-6662" email="info@chipotle.com" web="" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features=""/>
	<marker name="A4T" lat="45.1392640000" lng="-95.0523150000" category="Restaurant" address="3040 Excelsior Blvd" address2="" city="Minneapolis" state="MN" postal="55416" country="US" phone="612-922-6662" email="info@chipotle.com" web="" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features=""/>
	<marker name="AA4X4" lat="45.4370370000" lng="-117.2888080000" category="Restaurant" address="3040 Excelsior Blvd" address2="" city="Minneapolis" state="MN" postal="55416" country="US" phone="612-922-6662" email="info@chipotle.com" web="" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features=""/>
	<marker name="AADTCA" lat="42.7007840000" lng="-84.5490050000" category="Restaurant" address="3040 Excelsior Blvd" address2="" city="Minneapolis" state="MN" postal="55416" country="US" phone="612-922-6662" email="info@chipotle.com" web="" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features=""/>

**Comment by jmp100** [comment]
Is this project dead without issue support?

**Comment by GiancarloGomez** [comment]
Hey @jmp100 what issues are you experiencing? Have you turned on debugging?

**Comment by jmp100** [comment]
No issues reported with IE debugger & console. I can attach xml sample data of nearly 700 records for testing using the stock xml template.

**Comment by GiancarloGomez** [comment]
Hey @jmp100, I have contributed before to this project but I do not manage it. If you'd like I can offer some paid support.

**Comment by GiancarloGomez** [comment]
Before that though, I was referring to turning on debug mode on the plugin and seeing what is happening when the data comes in.

**Comment by jmp100** [comment]
Oh.. ok will try that..

**Comment by jmp100** [comment]
No debug info posting..

**Comment by GiancarloGomez** [comment]
You should see some stuff by enabling it. You see nothing at all? Can you paste the snippet code here of how you are instantiating the plugin.

**Comment by jmp100** [comment]
$(function() {
				$('#bh-sl-map-container').storeLocator({
					'dataType': 'xml',
					'dataLocation': 'data/locations2.php',
					'inlineDirections': true,
					'mapSettings': { zoom : 9, mapTypeId: google.maps.MapTypeId.ROADMAP },		
					'storeLimit': '26',
					'debug': 'true'
				});
			});

**Comment by GiancarloGomez** [comment]
and you see nothing coming back at all? Not even the XHR on your console? Test using Chrome as IE's debug is just a waste of time. See if you run into any issues there. Is the data coming back from your data location coming back as valid XML?

**Comment by jmp100** [comment]
Ok, it's posting in IE console. 0 errors, 1 warning.

More messages are being logged than the console can display. Only the first 1000 messages per second are shown.

**Comment by jmp100** [comment]
Attached is test data if you want to test locally.

[locations.xml.txt](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/files/1242885/locations.xml.txt)

**Comment by jmp100** [comment]
Attached is nearly 700 test records if you want to test locally. I'm out of ideas on this.

[locations.xml.txt](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/files/1242895/locations.xml.txt)

**Comment by GiancarloGomez** [comment]
I can offer paid support at this point if you’d like. You can email me at
support@fusedevelopments.com and I can review options with you.

Thank you,
Giancarlo Gomez
http://giancarlogomez.com

From: jmp100 <notifications@github.com> <notifications@github.com>
Reply: bjorn2404/jQuery-Store-Locator-Plugin
<reply@reply.github.com>
<reply@reply.github.com>
Date: August 22, 2017 at 1:50:52 PM
To: bjorn2404/jQuery-Store-Locator-Plugin
<jquery-store-locator-plugin@noreply.github.com>
<jquery-store-locator-plugin@noreply.github.com>
Cc: Giancarlo Gomez <giancarlo.gomez@gmail.com> <giancarlo.gomez@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [bjorn2404/jQuery-Store-Locator-Plugin] Win 10 / IE 11 breaks
with JSON or XML after 544 records (#189)

Attached is test data if you want to test locally.

locations.xml.txt
<https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/files/1242885/locations.xml.txt>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/issues/189#issuecomment-324102292>,
or mute the thread

**Comment by jmp100** [comment]
I would have to get approval from client. This is a bug issue with this script. Not sure how that will fly with them.

**Comment by GiancarloGomez** [comment]
I understand. If they approve you can email me and I can share with you my price sheet. Have a great day.

**Comment by jmp100** [comment]
Can you test with the above attached data and give some estimate for a fix? No issues in any browser except IE.. go figure.

**Comment by GiancarloGomez** [comment]
What version of IE requires support

**Comment by GiancarloGomez** [comment]
From this point on please contact me via email to further discuss.

**Comment by jmp100** [comment]
IE 11

**Comment by jmp100** [comment]
@bjorn2404 

Is this IE11 script bug issue on deck to be addressed? Test data linked above.

Thanks,
James

**Comment by bjorn2404** [comment]
@jmp100 My availability right now for providing free support for a free plugin is very limited at this time. This is the first I've heard of any potential issue specific to Internet Explorer but I can try to do some testing this weekend.

**Comment by jmp100** [comment]
Thanks bjorn2404, after 544 records IE 11 posts a location in the first position on the west coast when using a central Ohio zip. There are also Canadian locations in the feed. Some of the nearest locations do not post and not sorting by closest location asc. Also, default zoom settings do not work. No issues in Chrome, Firefox and Safari. No console errors reported in IE when debugging. The client reported the issue so the behavior is not unique to my machine.

			$(function() {
				$('#bh-sl-map-container').storeLocator({				
					'dataType': 'xml',
					'dataLocation': 'data/locations.xml',
					'inlineDirections': true,
					'mapSettings': { zoom : 9, mapTypeId: google.maps.MapTypeId.ROADMAP },		
					'storeLimit': '26',
					'debug': 'true'
				});
			});

Thanks,
James

[locations.xml.txt](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/files/1252115/locations.xml.txt)

**Comment by bjorn2404** [comment]
@jmp100 You are missing coordinates for location name 186, which seems to make IE 11 go haywire.

**Comment by jmp100** [comment]
Wow..., thanks bjorn2404, that completely got by me. Apparently for that record the postal code is not in the database. I'll set conditions to fix. Thanks again, this issue was on me.
