### ISSUE TITLE
Server-side clustering

### ISSUE THREAD

**Issue by kamov** [bjorn2404/jQuery-Store-Locator-Plugin#194]
I would like to know if possible with your plugin to implement server-side clustering like this 
https://github.com/biodiv/anycluster

demo: https://www.anymals.org/nx/bigmap/

This load new locations when you drag map or zoom map.

Thanks

**Comment by bjorn2404** [comment]
The plugin supports [MarkerClusterer](https://github.com/googlemaps/v3-utility-library/tree/master/markerclusterer) with the markerCluster setting. When set, that setting value (needs to be an object) gets passed in to the third parameter of the MarkerClusterer constructor (options object). https://googlemaps.github.io/js-marker-clusterer/docs/reference.html
