### ISSUE TITLE
Update map width

### ISSUE THREAD

**Issue by kamov** [bjorn2404/jQuery-Store-Locator-Plugin#195]
I am using jquery to show/hide the panel with all locations.
I need to resize the map when panel close or open.

This is the code:

google.maps.event.trigger(map, "resize");

But how to get "map" object from Store Locator?

Thanks

**Comment by bjorn2404** [comment]
Use one of the callbacks that has the map object such as callbackMapSet:

https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks.md

**Comment by kamov** [comment]
mmm... yeah this work great... 

I had already checked the callbacks, but for callbackMapSet for example is written 
"Fires after the map has been loaded."

This mean that it's fire only 1 time after the map has been loaded?

Thank you!

**Comment by kamov** [comment]
No, is not working always. I mean when you click on inline Directions, and then close directions, the map is not resized

**Comment by kamov** [comment]
I make this work by changing closeDirections callbacks.

```js
// Line 1482 - added map param
closeDirections: function(map) {
...
			// Close directions callback
			if (this.settings.callbackCloseDirections) {
				this.settings.callbackCloseDirections.call(this, map);
			}
...
}

// Line 2219 - added map param in closeDirections()

		inlineDirections: function(map, origin) {
...
				// Close directions
				$(document).on('click.'+pluginName, '.' + _this.settings.locationList + ' .bh-sl-close-icon', function () {
					_this.closeDirections(map); // Added map here
				});
			});
		},
```

And then I can use callback like:

```js

            callbackCloseDirections: function(map) {
                google.maps.event.trigger(map, "resize");
            },

```

Maybe there is another way?

**Comment by kamov** [comment]
No, is not working :(

I hope you have an idea, here is online:  TinyURL.com/y8sz8va8

You can see that toggle of left panel work fine, until you close inline directions.
Then stop work.

Thanks

**Comment by kamov** [comment]
@bjorn2404 did you get my email about custom work?

**Comment by neshaman** [comment]
Hello bjorn,

I love you plugins. Super nice work man.

I'm struggling getting the customized map marker on the map. 

I couldn't get how to for example change color on the map "pin" for specific item from the list?

Is something like this built in the plugin, or I need to look into some custom work?

This is critical piece in me trying to use your plugin, so any feedback would be much appreciated.

Thank you very much,

Nenad
