### ISSUE TITLE
Question about directions

### ISSUE THREAD

**Issue by kamov** [bjorn2404/jQuery-Store-Locator-Plugin#196]
I notice that Directions links appear only when you add an address in search.

And disappear when address is missing.

But how it work? I mean we have FROM and TO location, but which position is FROM?

For example, if I add Edina MN in your example, then appear _FROM Edina MN TO York Ave S Edina_.
But locations which you found should be TO, and FROM should be my current position, or editable (I Mean that user can insert FROM location).

Thanks!

**Comment by bjorn2404** [comment]
The form input is the from (origin) location. You change the from by submitting the form.
