### ISSUE TITLE
Renaming jQuery-Store-Locator-Plugin-master folder gives an error

### ISSUE THREAD

**Issue by PublicV0id** [bjorn2404/jQuery-Store-Locator-Plugin#198]
Hello

using apache server
and autocomplete-example.html

When **jQuery-Store-Locator-Plugin-master folder** is renamed

`<input type="text" id="bh-sl-address" name="bh-sl-address" placeholder="Oops! Something went wrong." value="Αθήνα" autocomplete="off" disabled="" class=" gm-err-autocomplete" style="background-image: url(&quot;https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png&quot;);">`

what is causing that error ?

**Comment by bjorn2404** [comment]
The dist directory has the files you want. There's no reason to have the full project root directory on a server.

**Comment by PublicV0id** [comment]
Hello 
Thanks for the quick response.
I have found what was causing that error ,
It was the api key .
When I added a new one it worked .
