### ISSUE TITLE
Any chances to speed it up?

### ISSUE THREAD

**Issue by suntrop** [bjorn2404/jQuery-Store-Locator-Plugin#205]
I've got about 500 locations and when I hit the search button it looks about ~ 6 seconds until the map shows … finishing the render process is fast though. There are about 400 locations more to come the next months.

If there are ways to speed things up, I would love to get some hints! Maybe removing the distance calc, reducing the templates? Switching from JSON to XML perhaps? Does clustering help?

I have read the tutorial on "thousands of locations" … but I'd like to have the JOSN file with all the locations.

**Comment by bjorn2404** [comment]
What else are you loading on the page? Doing inline Handlebars templates would be one thing with the listTemplateID and infowindowTemplateID settings.
