### ISSUE TITLE
Custom/multiple markers icons

### ISSUE THREAD

**Issue by neshaman** [bjorn2404/jQuery-Store-Locator-Plugin#207]
I love, love your work man. Thank you a ton.

I want to have numbers on the list and correspondent number on the markers but I can't figure out how to do it. I really tried.

The second would be, to have some markers different color depending on the value in the locations json file. Any suggestions how I can do that, or where in the js plugin I should look into achieving that.

I have very tiny timeline to do it and since I'm struggling to figure it out, any help would save me and I will highly appreciate it.

Thank you again for your awesome work.

**Comment by rmassoud** [comment]
Have you found a solution for this?

**Comment by neshaman** [comment]
I’ve solved the numbers issue with google-maps-utility-library-v3, but for the custom marker color I had to do with some messy looping through the list items...
