### ISSUE TITLE
json location without lat and long, but only city

### ISSUE THREAD

**Issue by itajackass** [bjorn2404/jQuery-Store-Locator-Plugin#213]
PLugin works very well, but i've a json file where some locations have only city set... and empty LAT and LONG.... These places then are placed by defaut in the middle of the world into the sea!!!
Is there a way to tell plugin to calculare distance by city if lat and long are empty for some locations?

**Comment by bjorn2404** [comment]
No, the locations need to be geocoded. The Geocoding API [has limits](https://developers.google.com/maps/documentation/geocoding/usage-limits) of 50/second and 2,500 per day. If you are geocoding locations on the fly you are much more likely to run into the limits.
