### ISSUE TITLE
Pass variable to script and initialize it only after a on click event?

### ISSUE THREAD

**Issue by itajackass** [bjorn2404/jQuery-Store-Locator-Plugin#215]
Is there a way to initialize plugin not on `$(document).ready` but, for example, on `$("#button").on("click")` ? I need this because i've to retrieve the full list of stores via ajax and i've to pass a variable $id to exclude a store itself by list...for example i've 4 stores: store1, store2, store3, store4.
If I click in a button for store1 `<button id_store="1">CHECK STORES AROUD ME</button>` i'd like to pass variable `id_store` to my ajax to search ALL STORES but not store1........

**Comment by bjorn2404** [comment]
The plugin passes specific parameters with the AJAX request but it's not currently set up so that you can add additional custom parameters. I might change this soon so you can pass additional things.

**Comment by itajackass** [comment]
Ok I hope you can implement it this option. Also is it possible to initialize the plugin only on ,for example, event click button instead of document.ready? Because i've a page where users can do somethings...and if they need can be do the search, but is not the rule...so i'd like to load big data from ajax only if needed...thanks

**Comment by bjorn2404** [comment]
A new ajaxData setting is available in v3.0.0 to pass custom parameters with the AJAX request.

**Comment by itajackass** [comment]
Thankyou. Can you tell me how to use this new feature for my purpose? I've tried to see documentation about ajaxData but i've not found any example.
My goal still remain: 1 load the page without initializing plugin. 2 if i click button A (with data-value=1) then load plugin passing the value=1 to retrieve all store with id != 1. If i click button B (data-value=2) retrieve all stores with id != 2 etc...

**Comment by itajackass** [comment]
I've tried this with no success. Plugin is not initialized correctly inside a event call, example here on click event:
	
	$(".btn-show").on("click", function(e) { //<---- I NEED THIS TO CHANGE id_store_start EVERY TIME

		e.preventDefault();
		
               var id_store_start = $(this).data("id");
		var city = $(this).data("city");

               $('#bh-sl-map-container').storeLocator({
		'dataType': 'json',
		'ajaxData': { 'id_to_exclude_from_search': id_store_start },
		'dataLocation': 'ajax/search.php',
		'distanceAlert': 300,
		'visibleMarkersList': true,
		'originMarker': true,
		'storeLimit': -1,
		'slideMap': false,
		'modal': true
	       });

		if ( city != "" ) {
			$("#bh-sl-address").val(city);
			$("#bh-sl-user-location").submit();
		} else {
			alert("City empty");
		}
		
	});

<a class="btn-show" data-id="1" data-city="New York">Nearby Store n.1</a>
<a class="btn-show" data-id="2" data-city="Miami">Nearby Store n.2</a>
<a class="btn-show" data-id="3" data-city="Chicago">Nearby Store n.3</a>
