### ISSUE TITLE
Coords pointing to somewhere in africa

### ISSUE THREAD

**Issue by openskies2009** [bjorn2404/jQuery-Store-Locator-Plugin#220]
I'm using csv. When I click on a location. no icon shows and the map points to no where near close to my csv file locations. When I manually hand pan in the google map. there is not a location there. Whats wrong?

**Comment by openskies2009** [comment]
and here's my csv file https://www.dropbox.com/s/plmr67zmberwucn/tccenterss.csv?dl=0

**Comment by bjorn2404** [comment]
![image](https://user-images.githubusercontent.com/303829/36006710-2c14141a-0d04-11e8-8e8b-7cc6e47149e5.png)

No idea why you think this plugin is compatible with a CSV file. Also assuming you have not geocoded your locations.
