### ISSUE TITLE
Error: Could not load plugin templates

### ISSUE THREAD

**Issue by flocoder** [bjorn2404/jQuery-Store-Locator-Plugin#221]
Hi @bjorn2404 ,
Firstly, thanks for making this plugin open source.
I am trying to install the plugin in my project at localhost. 
I am seeing this error  and couln't find anywhere to fix it.

**Error: Could not load plugin templates. Check the paths and ensure they have been uploaded. Paths will be wrong if you do not run this from a web server.**

I know it the paths are wrong for the templates but where should I fix them?

Any help would be highly appreciated. 

Thanks

**Comment by bjorn2404** [comment]
Please review the [options](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/options.md). The template settings are documented.
