### ISSUE TITLE
Conflicts Between Same City Name in Different Countries

### ISSUE THREAD

**Issue by dhruvangg** [bjorn2404/jQuery-Store-Locator-Plugin#222]
In My Data, I have "Bath" and "Birmingham" cities & both cities exists in UK and USA. My Coordinates and PIN Code are for UK. But result shows USA cities in MAP. So any Solution for this??

**Comment by bjorn2404** [comment]
Please review the [options documentation](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/options.md). regionID, callbackGeocodeRestrictions, callbackRegion, you could add the [region biasing parameter](https://developers.google.com/maps/documentation/javascript/examples/geocoding-region-es) to the maps call, etc.
