### ISSUE TITLE
Template locations relative path

### ISSUE THREAD

**Issue by michaelcurry** [bjorn2404/jQuery-Store-Locator-Plugin#23]
I had to edit the js file to allow for templates to work.  As you can see templates are in the correct directory, but the main directory is in a a subdirectory.  Please change the app to use relative paths so this will not be a problem for others.

My Change:

```
'infowindowTemplatePath': 'js/storeLocator/templates/infowindow-description.html',
'listTemplatePath': 'js/storeLocator/templates/location-list-description.html',
'KMLinfowindowTemplatePath': 'js/storeLocator/templates/kml-infowindow-description.html',
'KMLlistTemplatePath': 'js/storeLocator/templates/kml-location-list-description.html',
```

**Comment by flocoder** [comment]
@michaelcurry @bjorn2404 ,
As @michaelcurry suggested I need to make these URLs relative. Where can I change the code for that?
Thanks
