### ISSUE TITLE
Can we add OR operator to category filter ??

### ISSUE THREAD

**Issue by afrazahmmad** [bjorn2404/jQuery-Store-Locator-Plugin#235]
**Thanks for making this robust plugin.**

**Issue:**  I want to show only those markers which are selected from category filter.
Right now your [Category Filter](https://bjornblog.com/storelocator/v2/categories-example.html) filters markers with **and**  operator but I want to use it as **or** operator.
Can you please explain how to achieve this feature ??

**Comment by afrazahmmad** [comment]
**I found solution for my requirement**
I am working on a project (http://voddemo.akkastech.com/category/2) to make a store locator using this plugin. By default, this plugin applies **AND** operator on category filters but I wanted **OR** operator so that I can show all those markers that falls under selected filters. Luckily, I found regular expression in 
this plugin which applied filter using **AND**  operator. 
I just changed .**join('')** to **join('|')** and **OR** operator on category filter was successfully applied.

**Comment by bjorn2404** [comment]
@afrazahmmad The "exclusiveFiltering" setting is actually set up to make this switch. You'd set the value to true for "OR" functionality.

**Comment by afrazahmmad** [comment]
Last night I was reading your plugin code and I saw exclusiveFiltering and I said wow this man have done a really great job. 
Thanks for the **BEST** plugin for store locator.
