### ISSUE TITLE
How to use callbackGeocodeRestrictions?

### ISSUE THREAD

**Issue by TylerBarnes** [bjorn2404/jQuery-Store-Locator-Plugin#238]
Hi there, awesome plugin!
The plugin does everything I need but I'm having one issue.
I'm attempting to auto geolocate the user and display stores within the users state / province only. 
I think I should be using callbackGeocodeRestrictions but no matter what I return in the function it doesn't seem to apply any restrictions. [The documentation](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks/callback-geocode-restrictions.md) mentions the geocoding restrictions object can be overwritten but it doesn't mention how to do this. Help would be hugely appreciated. 
Thanks

**Comment by bjorn2404** [comment]
Please see [Component Filtering documentation](https://developers.google.com/maps/documentation/javascript/geocoding#ComponentFiltering) on Google for what properties should be defined in the override object. Documentation on how to use callbacks is [provided](https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks.md) and you just need to return the object in the callback function to override.

**Comment by TylerBarnes** [comment]
Hmm, I used both of those pages before asking the question but couldn't get it working. I'll give it another try this week.

Thanks @bjorn2404 !
