### ISSUE TITLE
"For development purposes only" google map error

### ISSUE THREAD

**Issue by Pete44131** [bjorn2404/jQuery-Store-Locator-Plugin#242]
Google is showing your sample map as "for development purposes only" with the map area grayed out.  I know this issue also popped up on our website only a week or two ago (from my knowledge).   Research states that you/I need to use an API key for the map now.  How is this fixed or where would the API key need to be added?

**Comment by crebelein** [comment]
No problem, Pete44131. Glad that I could help. When I first saw this come down the pike it caught me off guard as well. I was using a much much older version of the code and needed to upgrade the entire locator (including my dataLocation feed).

Don't feel bad about coding everything in Notepad either. I still do 95%+ of my development work in vi!
