### ISSUE TITLE
Multiple locator in 1 page

### ISSUE THREAD

**Issue by weeki584** [bjorn2404/jQuery-Store-Locator-Plugin#25]
Hi Bjorn,

Thank you for the awesome plugin!
It works great on my site but I was wondering is it possible to put 2 different store locator in 1 page? i tried to duplicate the file but it screwed up instead ^^"

Please advice how to solve this issue.
Many thanks in advance!

**Comment by shpemu** [comment]
TL/DR: I would also like to be able to do this.

The rest: I would like to automagically show the closest location as text at the top of a web page, then further down have the map of available locations show. I am able to do one or the other but not both on the same page. Any suggestions? I'm all ears. Thank you!
