### ISSUE TITLE
Multiple filters for one category should use OR instead of AND comparisons

### ISSUE THREAD

**Issue by tristangemus** [bjorn2404/jQuery-Store-Locator-Plugin#253]
Expected result: If I selected multiple filters within a category, I should see results for both filter A and B.

Actual result: When I select filter A, I see results for items with A. When I select filter B, I see results for items with filter B. When I select filter A & B, I see 0 results.

**Comment by bjorn2404** [comment]
@tristangemus See `exclusiveFiltering` setting.
