### ISSUE TITLE
exclusiveFiltering not working across filters

### ISSUE THREAD

**Issue by briankerrdesign** [bjorn2404/jQuery-Store-Locator-Plugin#269]
I have filter A (Brand) with a list of brands, and filter B (type) with a list of types. Each filters the results correctly, but when both are applied it is not filtered down using AND across both filters i.e. brand = x AND type = y. Want to drill down.

It is also not working on your example here - https://bjornblog.com/storelocator/v2/categories-example.html. When you select "Bar" under Category, 3 results come up. Then if you subsequently select "Online Ordering" from features, more results come up, not less (if it was drilling down).

I have tried all combinations of exclusiveFiltering and such.

**Comment by bjorn2404** [comment]
I believe this has been resolved since the issue was originally posted. I'm not able to replicate using the categories example file as described above.
