### ISSUE TITLE
ERROR: Automatic location detection failed. Please fill in your address or zip code.

### ISSUE THREAD

**Issue by joesparacio** [bjorn2404/jQuery-Store-Locator-Plugin#273]
We just started getting the "Automatic location detection failed. Please fill in your address or zip code" alert every time the map loads in Chrome and Edge. It's not happening in Safari and FF (after allowing location). We updated the source files to the latest found in this repo. Any other suggestions? Has been working flawlessly prior to a couple weeks ago.

**Comment by varunsood** [comment]
@joesparacio Are you able to fix this?

**Comment by joesparacio** [comment]
Yes, we realized geolocation failed because we had set "geolocation: none" in the Features Policy, which Chrome and Edge strictly adhere to. Safari and Firefox ignore this setting.
