### ISSUE TITLE
Zoom issue after filtering by category and with some other settings

### ISSUE THREAD

**Issue by bjorn2404** [bjorn2404/jQuery-Store-Locator-Plugin#278]
A [change in the Google Maps Javascript API](https://developers.google.com/maps/documentation/javascript/releases#2022-03-24) with `fitBounds` on 3/24/22 has created problems in the plugin with zooming with certain settings enabled such as `taxonomyFilters`. Currently investigating whether this is a bug with the plugin or with the API itself.

As a temporary workaround you can specify the previous version when loading the API, such as:

`<script src="https://maps.google.com/maps/api/js?v=3.47"></script>`

**Comment by thinkingcap** [comment]
Using 
`fullMapStart: true,
storeLimit: -1,
` 
The map looks good on initial load then I get a zoomed out maps when I apply a filter.
If Im not displaying all 700 locations it doesnt have this issue.

**Comment by thinkingcap** [comment]
When I apply the filter it looks the same as #237

**Comment by thinkingcap** [comment]
Update: This was due to invalid lat|long co-ordinates in my location data, once corrected it zoomed as expected.
