### ISSUE TITLE
Category filtering with JSON data: markers duplicate when Reset is selected and then selected again.

### ISSUE THREAD

**Issue by VinodSoftcripts** [bjorn2404/jQuery-Store-Locator-Plugin#293]
Hello,

Demo: http://54.156.167.50/demo/index.html

Steps to reproduce:

Select "Water Island" in the Islands dropdown, and you will see 5 locations on the map.
Click the reset button and wait for the map to reload.
Then select "Water Island" again, and you will see duplicated locations for each marker.

Any help would be appreciated. 

Thanks.

**Comment by bjorn2404** [comment]
Thanks, yeah I'm able to replicate this and it looks like a bug. Will be looking into it more.

**Comment by bjorn2404** [comment]
@VinodSoftcripts There's a fix pushed to the development branch https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/tree/development

I may add one or two additional items before the next release but the above should cover it until then.

**Comment by VinodSoftcripts** [comment]
@bjorn2404 

Thank you for sharing the link to the fix on the development branch. I appreciate your prompt response and assistance. This fix will be really helpful for us until the next release.

**Comment by bjorn2404** [comment]
Issue fixed in release 3.1.11. Thanks for reporting!
