### ISSUE TITLE
Directions not working

### ISSUE THREAD

**Issue by HarldVerbiesenVIPMarketingBV** [bjorn2404/jQuery-Store-Locator-Plugin#304]
1e of all Awesome tool mate!!

FYI

Directions did not work.
Changed urls:

https://maps.googleapis.com/maps?saddr=???&daddr=???
To
https://www.google.com/maps/dir/?api=1&origin=????&destination=???

in  location-list-description.html

Now it works fine.

(lazyLoadMap:true,)

**Comment by bjorn2404** [comment]
@HarldVerbiesenVIPMarketingBV Thanks for the report! I'll get a patch out to fix.

**Comment by HarldVerbiesenVIPMarketingBV** [comment]
Thanks!  Have a nice holiday!
