### ISSUE TITLE
Marker cluster

### ISSUE THREAD

**Issue by herooutoftime** [bjorn2404/jQuery-Store-Locator-Plugin#33]
Would be a nice enhancement to add marker clustering ability.
Had to implement a really basic approach myself but could be done far more extensive.

To apply it:

```
...
,'markerCluster': true
,'markerClusterStyles': [{
		url: 'cluster1.png'
		,width: 90
		,height: 67
		,anchor:[11,37]
		,textColor: '#ffffff'
	},{
		url: 'cluster2.png'
		,width: 90
		,height: 67
		,anchor:[11,37]
		,textColor: '#ffffff'
	},
...
```

And in the plugin itself like this:

```
...
if(_this.settings.markerCluster === true) {
	var markerCluster = new MarkerClusterer(map, markers, {
		'styles': _this.settings.markerClusterStyles
	});
}
...
```

**Comment by chuck808** [comment]
Could you please let me know whereabouts this goes

...
if(_this.settings.markerCluster === true) {
    var markerCluster = new MarkerClusterer(map, markers, {
        'styles': _this.settings.markerClusterStyles
    });
}
...

Thanks

**Comment by ddalli** [comment]
@chuck808, I placed it on line 1890 in jquery.storelocator.js; however, this may differ from yours, for I have various additions/edits throughout the doc.. Nevertheless, I have it directly below the code that sets the list li background colors... 

Search for the comment: "// Add the list li background colors" in your doc... and place it under that.

**Comment by chuck808** [comment]
Hi ddalli,

Sorry for the delayed response. I haven't had time to give it a go yet but thank you very much for your help.

**Comment by angeenes** [comment]
Thanks, works great except for the markerClusterStyles , for some reason, I can't make it work, anyways, just use  'markerCluster': true,   and then it all works fine ! :+1:

**Comment by e-void** [comment]
Having problems implementing this, can someone share a link to working example.
Thanks.

**Comment by bjorn2404** [comment]
I've added support for Marker Clusterer in v2.6.0 with the new markerCluster setting. When set, that setting value (needs to be an object) gets passed in to the third parameter of the MarkerClusterer constructor (options object). https://googlemaps.github.io/js-marker-clusterer/docs/reference.html
