### ISSUE TITLE
How to show nearest store with infobox on map by default

### ISSUE THREAD

**Issue by wyamout** [bjorn2404/jQuery-Store-Locator-Plugin#39]
How to show the nearest store on the map by default  showing the infobox no matter how far it is?

**Comment by bjorn2404** [comment]
This is a custom request, not an issue with the plugin. I'd suggest finding a programmer to do it for you or I'm also taking paid customization requests on my blog.

**Comment by wyamout** [comment]
@bjorn2404 I sent you an email regarding paid customization 2 weeks ago, are you still doing that?

**Comment by bjorn2404** [comment]
@wyamout Sorry, I'll reply to your email tomorrow.
