### ISSUE TITLE
originMarkerImg bug

### ISSUE THREAD

**Issue by Redani** [bjorn2404/jQuery-Store-Locator-Plugin#40]
Hi Bjorn,

I have submitted some other issues in my previous post which is closed, are you still receiving notifications??

**Comment by Redani** [comment]
Thank you for your reply, but I'd just like to know if you're welling to supply any support for your plugin???  I'm still stuck and there are so many other things that are not functioning correctly... :/

**Comment by bjorn2404** [comment]
Fixed originMarkerImg bug and added click callbacks in v2.0.5.

**Comment by Redani** [comment]
Thank you for your work.

1- In my case, i need to run a same portion of code when a list element or marker are being closed. Is it possible to do something like: callbackListClick, callbackMarkerClick: function() { ... } ??

2- what about a callBack function when storeLocator is loaded (previous callbackComplete) ?

3- to search for places, i have a form that contains: ZipCode, Address and Country. In your js file I replaced `data: {
	'origLat' : lat,
	'origLng' : lng,
	'origAddress': address
}`
by
`data: $("#bh-sl-user-location").serialize()`

but it looks like the search is performed ONLY when the textbox "#bh-sl-address" is being changed! is that normal?

Thank you very much
