### ISSUE TITLE
Problem with the same zip code in both sides

### ISSUE THREAD

**Issue by nncl** [bjorn2404/jQuery-Store-Locator-Plugin#41]
Hi.

If I put a zip code that is the same of the zip code on json or xml file It was supposed to appear of distance 0 mile. But I've tested and the address does not appear. What's happened?

Thanks.

**Comment by nncl** [comment]
Hi.

I'm sorry but I did some tests and apparently was cache problem.

Thanks.

**Comment by bjorn2404** [comment]
Glad you figured it out.
