### ISSUE TITLE
Passing zip code to dataLocation

### ISSUE THREAD

**Issue by yoxalld** [bjorn2404/jQuery-Store-Locator-Plugin#42]
Is there a way to pass the zip code from the form to the dataLocation file that we specify? My data is created dynamically from another service and they need to know the zip code in order to return to correct information. Thanks!

**Comment by bjorn2404** [comment]
Latitude, longitude and the address (what they enter into the search form) are passed over by default. origLat, origLng, origAddress.

**Comment by yoxalld** [comment]
That's great! I misunderstood the address to be a street address but I understand now. Thanks for the clarification!

**Comment by davemerwin** [comment]
For those not familiar with how to do this, can you show an example? Could it work something like: 

'dataLocation': '/api/locations?postal=' + origAddress + '&format=json'

thoughts?

**Comment by davemerwin** [comment]
I've tried the above and 'dataLocation': '/api/locations?postal=' + address + '&format=json' and I get the following error: Uncaught TypeError: Cannot read property 'distance' of undefined
