### ISSUE TITLE
Sort by country first

### ISSUE THREAD

**Issue by mwdelaneytwg** [bjorn2404/jQuery-Store-Locator-Plugin#43]
Hello, 
I'm running the 1.x version of this tool, and it's working great, but my client wants results to be sorted first by the country of the address entered, then by nearest, so that locations within the search radius, but over a national border, are shown last rather than first.

Is this possible?

Thanks!

**Comment by bjorn2404** [comment]
Not without customizations. With 2.x you can have a country drop-down select field and use the regionID setting to allow visitors to choose a specific country but that's as close as you're going to get without further custom work.
