### ISSUE TITLE
IE9 and IE8 Error

### ISSUE THREAD

**Issue by five-oh3** [bjorn2404/jQuery-Store-Locator-Plugin#44]
Great plugin, amazing work!  Found a small bug on IE9 and 8, any suggestions on how to resolve?  Looks like the following causes an error on these versions of explorer:  "for (var key in this.attributes) {"

Once user types in their search, error will not display map or listings in these versions of IE.

Any suggestions on how to make the plugin work with these versions?  Thank you so much!!
![screen shot 2015-01-21 at 3 50 35 pm](https://cloud.githubusercontent.com/assets/10642333/5846934/3ee8c736-a185-11e4-97f4-b84bca1fa07a.png)

![screen shot 2015-01-21 at 3 44 05 pm](https://cloud.githubusercontent.com/assets/10642333/5846942/460656fa-a185-11e4-8b97-35de98393494.png)

**Comment by bjorn2404** [comment]
Thanks, also seeing the same thing in those browsers. It's a lower priority for me at the moment but I will get to it.

**Comment by five-oh3** [comment]
Thank you so much, really appreciate it - love your work.  Thank you for sharing the plugin with the community!

**Comment by bjorn2404** [comment]
Sorry I never got around to this but these are just not relevant browsers anymore so I'm closing this.
