### ISSUE TITLE
How do I get the JSON example latitude and not lat ?

### ISSUE THREAD

**Issue by Infinitanet** [bjorn2404/jQuery-Store-Locator-Plugin#45]
Hello.
  I am using this plugin to ad an extension of Joomla.

  How do I get the plugin the value of latitude and longitude, by default it takes "lat" and "lng"?

  Thank U!

**Comment by bjorn2404** [comment]
Assuming you're outputting the JSON with PHP can't you just rewrite the keys before json_encode? http://stackoverflow.com/questions/5917496/change-json-key-name-json-generated-using-json-encode
