### ISSUE TITLE
Custom marker with correlation letter

### ISSUE THREAD

**Issue by mnantel77** [bjorn2404/jQuery-Store-Locator-Plugin#46]
Hi when I add some custom markers all the markers lost theirs correlation letter?

**Comment by bjorn2404** [comment]
The letters are part of the Google markers and will not overlay custom markers. If you're talking about the letters in the list, when you set the store limit to a number greater than 26 that's more than the English alphabet so the letters don't display.

**Comment by mnantel77** [comment]
Ok thanks!
