### ISSUE TITLE
Only one search on city

### ISSUE THREAD

**Issue by philipehsing** [bjorn2404/jQuery-Store-Locator-Plugin#47]
Hi, I have modified the search on city to country. This problem occurs even if I run the city. The problem is that they only go to filter once, I search in germany it works, I make then a new search on France so there will not be a new search but it only shows the old results in germany. What is this?

Thanks for a great plugin beyond it :)

**Comment by bjorn2404** [comment]
Is the built in category filtering not adequate for this? You might have better luck using that: http://www.bjornblog.com/storelocator/v2/categories-example.html
