### ISSUE TITLE
Hide map

### ISSUE THREAD

**Issue by philipehsing** [bjorn2404/jQuery-Store-Locator-Plugin#48]
Hey! 

How can i hide the map without destroy the result-list? If i hide the map my result list dont show...

**Comment by bjorn2404** [comment]
Can't you just target the #bh-sl-map div?

**Comment by philipehsing** [comment]
What do u mean? De results doesnt show if i set css display none or remove the map from dom.

**Comment by bjorn2404** [comment]
Yes, that can work with CSS or jQuery, etc. Keep in mind though that it's against the Google Maps TOS to use its geocoding service without showing a Google Map. So, to stay in compliance you'll need to show the map at some point.

**Comment by cleverjaime** [comment]
hi, I just wanna ask if is it possible to add a lazy loading for the store list? Instead of using pagination use lazy loading

**Comment by bjorn2404** [comment]
@cleverjaime It's not something I'm planning on adding in the near future but I might consider it at some point. Completely focused on making a WordPress version of the plugin right now.
