### ISSUE TITLE
fullMapStart + inlineDirections bug

### ISSUE THREAD

**Issue by milansimek** [bjorn2404/jQuery-Store-Locator-Plugin#52]
When fullMapStart is enabled, inline directions don't work.

I fixed is by changing the following:

in method directionsRequest on line 1032:

Change:

    if(destination) {

to:

    if(destination && origin) {

Maybe there is a more elegant fix, but this works for me at the moment.

Thanks for the great plugin by the way!

**Comment by milansimek** [comment]
Actually this is a better fix, the directions click listener registers twice, it can be solved as follows:

Change:

    if(_this.settings.inlineDirections === true){

To:

    if(_this.settings.inlineDirections === true && typeof firstRun === "undefined"){

**Comment by bjorn2404** [comment]
Thanks, I think I might go with the following since the origin has to exist for directions to work but either appear to fix the issue:

    if(_this.settings.inlineDirections === true && typeof origin !== 'undefined'){

**Comment by milansimek** [comment]
Hi Bjorn,

Sounds good to me. Your version should make the code more solid for various cases.

Thanks!

**Comment by bjorn2404** [comment]
Updated in v2.0.6.
