### ISSUE TITLE
CatMarkers and blank grey map if NoResults

### ISSUE THREAD

**Issue by angeenes** [bjorn2404/jQuery-Store-Locator-Plugin#53]
Hi,

Anyone getting the same issue on the catMarkers ?

When I use catMarkers with the following code

			'catMarkers' : {
						'Régional' : [''picto_map_regional.svg', 64, 64],
						'National' : [''picto_map_national.svg', 64, 64],
						'Local' : [''picto_map_local.svg', 64, 64],
							},

They do display correctly but when I have a no results answer, I get the grey blank map.
If I do not use catMarkers ( I comment them ), the normal behavior for NoResults works.

Any clue plz ?

**Comment by bjorn2404** [comment]
How are you testing the no results?

**Comment by angeenes** [comment]
Hi, I did so many changes that I can't find why I had that....Will get back to you if I see it again.Closing the issue then. Thanks anyways.
