### ISSUE TITLE
featured locations always displayed, possible ?

### ISSUE THREAD

**Issue by angeenes** [bjorn2404/jQuery-Store-Locator-Plugin#55]
Hi,

I am wondering how could I always display the featured location ? I know this is not implemented in the plugin.

the featured locations would always be displayed on the list and always displayed on the map no matter which filters and/or location searches are.

If you can point me to the right direction on your functions, I can try to do it, basically I think it would be to filter everything except the featured ones.

**Comment by jahid284** [comment]
You may use originMarker set to true to show a marker always visible for all categories

**Comment by bjorn2404** [comment]
The featuredLocations setting has been included since v1.4.7, which was released in 2013.
