### ISSUE TITLE
maxDistance Doesn't show results

### ISSUE THREAD

**Issue by sirlothos** [bjorn2404/jQuery-Store-Locator-Plugin#56]
I have a fully working slocator on my page showing all results. When I enter a zip code, it shows up to 1,700 radius. I am trying to limit the amount of miles on the index file by adding the 'maxDistance':true to 100 but nothing shows up after that. Same thing if I enable the little dropdown,

Can you please help?

Here is the code:

<script>
			/*
			$(function() {
				$('#map-container').storeLocator({
		            'slideMap' : false,
					'defaultLoc': false,
		            'fullMapStart': false,
					'maxDistance': true,
					//'maxDistanceID':'100',
					'distanceAlert': -1
					//'defaultLat': '26.230187',
					//'defaultLng' : '-80.1401912'
					//autoGeocode: true
         
				});
			});

			*/
			$(function() {
				$('#map-container').storeLocator({'maxDistance': true});
			});

		</script>

Thank you much!

**Comment by sirlothos** [comment]
/*
			$(function() {
				$('#map-container').storeLocator({
		            'slideMap' : false,
					'defaultLoc': false,
		            'fullMapStart': false,
					'maxDistance': true,
					//'maxDistanceID':'100',
					'distanceAlert': -1
					//'defaultLat': '26.230187',
					//'defaultLng' : '-80.1401912'
					//autoGeocode: true
         
				});
			});

**Comment by bjorn2404** [comment]
Copied the settings above into my maxdistance-example.html file and I'm not seeing any issues. If you want to limit by 100 create the select input field, set it to 100 and hide it with CSS. maxDistanceID doesn't accept a number like you have commented out above. Also make sure you have all your locations geocoded with a lat and lng. Does your console give any errors?

**Comment by sirlothos** [comment]
I have the select input field already in place. The thing is when I turn the MaxDistance to 'true' it stops showing the locations.

**Comment by sirlothos** [comment]
<input type="text" id="bh-sl-address" name="bh-sl-address" />
			  <select id="bh-sl-maxdistance" name="bh-sl-maxdistance">
				<option value="100">100 Miles</option>
              </select>

**Comment by bjorn2404** [comment]
Do you have an example link or can you check your browser's web development tools console to see if there are any JavaScript errors?
