### ISSUE TITLE
Stores Count

### ISSUE THREAD

**Issue by monocraft** [bjorn2404/jQuery-Store-Locator-Plugin#57]
Hi Bjorn,
Is there a way to get the count of the found location after search?
Thank you for sharing this.

**Comment by bjorn2404** [comment]
Hello,

Currently there is not but you can modify the callbackSuccess to do it. If you're using XML you can update on 1561:

    _this.settings.callbackSuccess.call(this);

to:

    _this.settings.callbackSuccess.call(this, $(data).find(_this.settings.xmlElement).length);

With JSON:

    _this.settings.callbackSuccess.call(this, data.length);

**Comment by monocraft** [comment]
Do you have any example with callbackSuccess?  I implemented that change but how would I access the data.length from front end?

**Comment by monocraft** [comment]
I couldn't figure out how you use callback so I just edit the source directly to give me the show store vs the total.
```javascript
#line 1980
$('#write span').text(storeNumToShow + " Out of "+ data.length);
```

**Comment by bjorn2404** [comment]
You'd do it like this:

    $('#map-container').storeLocator({
        'callbackSuccess' : function ( dataLength ) {
             $('#something').text( dataLength );
        }
    });

**Comment by monocraft** [comment]
Thank you Bjorn.  Very clean.

**Comment by monocraft** [comment]
I wanted the current number on the list also so I created another callback.
```javascript
#line 88
'callbackStoreNum'         : null,
```

```javascript
#line 1800
			// Callback callbackStoreNum
			if (_this.settings.callbackStoreNum) {
				_this.settings.callbackStoreNum.call(this, storeNumToShow, data.length);
			}
```
