### ISSUE TITLE
Handlebars {{niceURL pretags}}

### ISSUE THREAD

**Issue by monocraft** [bjorn2404/jQuery-Store-Locator-Plugin#58]
You have a pretag in your template that use niceURL but where is this defined?

**Comment by bjorn2404** [comment]
In init around line 126.

**Comment by monocraft** [comment]
Thank you again.  I want to use your niceURL to clean up some html tag but it saw it only remove https:// and http:// so I added another.
```javascript
Handlebars.registerHelper('strip-scripts', function(context) {
      var html = context;
      return new Handlebars.SafeString(html);
    });
```
