### ISSUE TITLE
inlineDirections: getAddressByMarker

### ISSUE THREAD

**Issue by jiggo** [bjorn2404/jQuery-Store-Locator-Plugin#60]
at line 1034 of jquery.storelocator.js (```getAddressByMarker``` function):

```var formattedAddress = null;```

results in a string with a ```null``` concatenated at the beginning, which makes directions fails on the destination address.

I suggest to initialize with an empy string:

```var formattedAddress = '';```

**Comment by bjorn2404** [comment]
Thanks, yes I already have this fixed in the development branch. Just working through one other thing but it should get merged in within a day or two.

**Comment by jiggo** [comment]
You're right, didn't noticed. Closing.

Thanks.
