### ISSUE TITLE
How to add map styling with "Snazzy" ?

### ISSUE THREAD

**Issue by swizenfeld** [bjorn2404/jQuery-Store-Locator-Plugin#61]
Would like to add map styling using https://snazzymaps.com/style/18566/red-darkness
but not sure where I could insert the code any help would be appreciated. 

Thank you!

**Comment by swizenfeld** [comment]
//Google maps settings
              if((settings.fullMapStart === true && firstRun === true) || settings.zoomLevel === 0){
                var myOptions = {
                    mapTypeControlOptions: {
                      mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'map_style']
                  }
                };
                var bounds = new google.maps.LatLngBounds ();
              }
              else{
                var myOptions = {
                  zoom: settings.zoomLevel,
                  center: new google.maps.LatLng(orig_lat, orig_lng),
                  mapTypeControlOptions: {
                      mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'map_style']
                  }
                };
              }
              var styles = [
                    // COPY CODE HERE
                ];

              var styledMap= new google.maps.StyledMapType(styles,{name: 'Styled Map'});

              var map = new google.maps.Map(document.getElementById(settings.mapDiv),myOptions);

              map.mapTypes.set('map_style',styledMap);

              map.setMapTypeId('map_style');

              $this.data('map', map);

**Comment by sarahpedley** [comment]
For anyone else who needed help on this issue you can add the styles within the map settings like so:

```
'mapSettings': { 
          zoom : 14,
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          styles: [{"featureType":"water","elementType":"geometry","stylers":[{"color":"#e9e9e9"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#ffffff"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#dedede"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#f2f2f2"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]}]
        }
```
