### ISSUE TITLE
Map not being displayed when having mapSettings 

### ISSUE THREAD

**Issue by soissons** [bjorn2404/jQuery-Store-Locator-Plugin#62]
```javascript
$(function() {
    $('#map-container').storeLocator({
        'mapSettings' : {
        },
    });
});
```
Added this to the index.html example.

Load page, type in "434", and the map is being loaded. Now type in "Minnetonka" and the map doesn't load.

**Comment by bjorn2404** [comment]
The mapSettings option is an override that allows you to set any Google Maps settings that you would normally use with Google Maps. You need to at least add zoom and the map type for it to work. 

    'mapSettings'              : {
			zoom     : 12,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		},

**Comment by soissons** [comment]
My bad. Thanks.
