### ISSUE TITLE
callbackFilters documentation

### ISSUE THREAD

**Issue by ideopia-curts** [bjorn2404/jQuery-Store-Locator-Plugin#63]
I'd like to clear a filter based on an if statement in the callbackFilter function. I've got 2 taxonomyFilters being filtered by two different select dropdowns (country and state). If someone selects 'US' in the country dropdown, a second dropdown with states appears. If someone selects a country other than 'US' in the first dropdown, I'd like to clear the 'states' filter. I couldn't find any documentation on how to clear a filter. Thoughts?

**Comment by bjorn2404** [comment]
Added callback documentation with v2.7.0 and reset functionality that can be triggered with an HTML element with the "bh-sl-reset" CSS class.  https://github.com/bjorn2404/jQuery-Store-Locator-Plugin/blob/master/callbacks.md
