### ISSUE TITLE
Will only show 45 results

### ISSUE THREAD

**Issue by mathiassen1990** [bjorn2404/jQuery-Store-Locator-Plugin#65]
Hi,

Btw great plugin!

I have this problem, i get a reseller list with 170 resellers.
But it can only show 45.
When i try to show more than 45 its like the plugin don't run..

- This is my result list in JSON http://jsfiddle.net/mathiassen1990/32tvfkte/1/
- And here is how i run it http://jsfiddle.net/mathiassen1990/dL1723jo/

My guess is that there is some sort of error in the results, but can't find it. And i get no error message in my console.

Really hope you can help :)

Best regards 
Christian.

**Comment by bjorn2404** [comment]
Did you figure this out? Otherwise, can you provide a link to the URL of the site?
