### ISSUE TITLE
distance in Miles is too different

### ISSUE THREAD

**Issue by techsaqib** [bjorn2404/jQuery-Store-Locator-Plugin#66]
Hi ,, i am using your plugin and i add a place which is approx 8km away from my location 
but the plugin show 500miles away , is your plugin calculate wrong , or its not take the current location to calculate , i  also set default location to my current latitude and logintude 

thanks please reply , i also able to get the paid support if you like to provide :) 

my email is fahimegold@gmail.com 
skype id is techsaqib

**Comment by bjorn2404** [comment]
Do you have an example on line that can be viewed? Are you sure the initial location is in the correct country?
