### ISSUE TITLE
Add var to request using callbackBeforeSend

### ISSUE THREAD

**Issue by yoxalld** [bjorn2404/jQuery-Store-Locator-Plugin#67]
Hi,
Just want to start by saying I really appreciate the effort you put into this plugin! It is a really cool bit of functionality.

I am wondering if there is a way to add an additional var to the request that gets sent to the dataLocation. I am building my list of locations from a third party service that requires that I use a zip code(this is all done through the file I point dataLocation to). 

The plugin currently works fine when I use a zipcode to search, However I want people to be able to search using an address as well. I have written some code to use google's geocaching service to look up and retrieve the zip code using the callbackBeforeSend option. However I don't know how to add this piece of data to the request that gets sent to the datalocation.

Am I using the correct callback to try this or is there a better way to accomplish this? Any help would be greatly appreciated.

**Comment by bjorn2404** [comment]
I don't think there's currently a way to do that without modifying the plugin. callbackBeforeSend just allows you to do something before the AJAX request. As far as I know, you can't pass something back to the original function where the callback is executed.

**Comment by yoxalld** [comment]
Yeah after doing some more research it looks like I would have to modify the plugin so that it ties all the callback functions as well as the ajax request together using promises. I don't really know much about them so I guess I have some more research to do. Thanks for the help!

**Comment by bjorn2404** [comment]
If you just want to modify the plugin you could probably move your geocaching code into the _getData method under the Remote Data comment (in the else) and then just add the data you want to in the AJAX request below that. I'd make the AJAX data setting a variable that could be changed with the plugin settings but I'm assuming that could be more of a security issue.
