### ISSUE TITLE
Wrong directions after searching for a new city / state

### ISSUE THREAD

**Issue by simonemonetti** [bjorn2404/jQuery-Store-Locator-Plugin#70]
Hi there and thanks for your great plugin.
I noticed a bug with inline directions.

If I select a city (ie: New York) and then I make another search in another city (ie: Chipotle), the first time "Get directions" link gets clicked it shows the right distance from each point on the map but it opens directions' box showing the previous city as starting point.
In this case, it will show directions starting from New York instead of Chipotle.

![schermata 2015-09-18 alle 02 37 36](https://cloud.githubusercontent.com/assets/3648918/9949541/4a1109bc-5dae-11e5-831d-742dd76fe8d0.png)

![schermata 2015-09-18 alle 02 37 11](https://cloud.githubusercontent.com/assets/3648918/9949540/4a108ed8-5dae-11e5-8939-6c66fe6d6e4a.png)

It happens only on the first directions request after searching for a new city, maybe the screenshot could help understanding the problem.
You can also see that it creates a new close icon everytime a new inline directions box gets opened.

Thanks in advance,
S.

**Comment by bjorn2404** [comment]
Thanks, I'm able to replicate this and will work on fixing it. Just wanted to note that there's a separate option for search locations by name with the nameSearch option. Chipotle is the name of a restaurant and not a city.

**Comment by simonemonetti** [comment]
Ouch!
I made the wrong example, in my specific case I'm using only cities and not restaurants or specific categories while encountering the bug.
I'll try with the name search option too, as you suggested.

Thanks a lot for the explanation and the support @bjorn2404 , I really appreciate that.

**Comment by bjorn2404** [comment]
@simonemonetti Should all be fixed in the current release of v2.1.0.

**Comment by simonemonetti** [comment]
Thanks so much for your support @bjorn2404 , I just tested it and everything seems ok now. I'll try to give my contribute for future releases and to offer your a beer via Paypal as soon as possible
