### ISSUE TITLE
Map Tiles not showing at all

### ISSUE THREAD

**Issue by ndimatteo** [bjorn2404/jQuery-Store-Locator-Plugin#71]
Hello,

I've been using your plugin for a while now on a client site, and recently the Map Tiles stopped showing entirely. I'm not getting any console errors, and the functionality is working perfectly otherwise.

Take a look at the page below to see what I'm talking about (scroll down or click "find an advisor"):
http://www.garrettinvestmentadvisors.com/

**Comment by bjorn2404** [comment]
@ndimatteo Have you updated the site's styling recently? If I disable the primary style.min.css stylesheet the map appears. I would watch out for any global "canvas" declarations but it could be some other styling conflict with Google Maps.

**Comment by ndimatteo** [comment]
@bjorn2404 odd, I haven't. But I'll try to comb through it to see if there's something causing it. Thanks!
