### ISSUE TITLE
Importing CSV

### ISSUE THREAD

**Issue by Amieman** [bjorn2404/jQuery-Store-Locator-Plugin#72]
Hey everyone, I'm sorry but I'm a complete newbie here.. I'm trying to figure out how to get my locations in here without having to do a ton of work. I have 350 location in a csv file is there anyway of getting them into the locations.xml file easily?

**Comment by bjorn2404** [comment]
@Amieman You'd want to convert the CSV to XML or JSON. If you search Google for converting CSV to XML or JSON you should find several methods.

**Comment by Amieman** [comment]
Thank you so much for your reply! My question is though how I go about the formatting? How do I endure it will be similar to the xml like so

<marker name="Chipotle St. Paul" lat="44.945127" lng="-93.095368" category="Restaurant, Coffee" address="29 5th St West" address2="" city="St. Paul" state="MN" postal="55102" country="US" phone="651-291-5411" email="info@chipotle.com" web="http://www.chipotle.com" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features="Fresh Guacamole" />

**Comment by Amieman** [comment]
<marker name="Chipotle St. Paul" lat="44.945127" lng="-93.095368" category="Restaurant, Coffee" address="29 5th St West" address2="" city="St. Paul" state="MN" postal="55102" country="US" phone="651-291-5411" email="info@chipotle.com" web="http://www.chipotle.com" hours1="Mon-Sun 11am-10pm" hours2="" hours3="" featured="" features="Fresh Guacamole" />

**Comment by bjorn2404** [comment]
It depends on the converter you are using but I'd try to make sure the CSV column names are the same as the XML attributes.

**Comment by Amieman** [comment]
Thanks! You rock!
