### ISSUE TITLE
Google map grey background

### ISSUE THREAD

**Issue by julienwangchang** [bjorn2404/jQuery-Store-Locator-Plugin#73]
Hi,
Since today I get grey background on my Google map. 
Pins are on the map but the map background is not there.

Is it a known issue ? Could you help me please ?

Thanks

**Comment by bjorn2404** [comment]
@julienwangchang Hard to know without seeing an example but it's likely a styling issue. Try disabling your stylesheets to see if the map appears. Watch out for global canvas element styling, etc. Also make sure that you're setting the zoom and mapTypeId if you're using the plugin's mapSettings option.

**Comment by julienwangchang** [comment]
Hi,
this is not a css issue, but a google map api issue.
As you can see here: http://www.emdr-france.org/web/annuaire/
The map wouldn't load.
We use the latest version of the plugin.

Here is our code: 

jQuery('#map-container').storeLocator({
      'mapSettings' : {
        zoom : 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      },
      'slideMap' : true,
      'nameSearch': true,
      'storeLimit': -1,
      'pagination': true,
      'loading': true,
      'locationsPerPage': 20,
      'autoGeocode': true,
      'lengthUnit': 'km',
      'kilometerLang': 'kilomètre',
      'kilometersLang': 'kilomètres',
      'noResultsTitle': 'aucun résultat',
      'noResultsDesc': 'Aucun praticien n\'a été trouvé. Veuillez choisir d\'autres critères.',
      'distanceErrorAlert': 'Malheureusement, le praticien le plus proche est à plus de ',
      'autoGeocodeErrorAlert': 'La détection automatique de votre lieu n\'a pas fonctionné. Renseignez une adresse ou un code postal',
      'addressErrorAlert': 'Impossible de trouver l\'adresse',
      'nextPage': 'Page suivante',
      'prevPage': 'Page précédente',
      'callbackListClick': function(){
        jQuery('.external-modal').magnificPopup({
          type: 'iframe'
        });
      },
      'callbackSuccess': function(){
        jQuery('.external-modal').magnificPopup({
          type: 'iframe'
        });
      },
      'callbackFilters': function(){
        jQuery('.external-modal').magnificPopup({
          type: 'iframe'
        });
      },
      'callbackPageChange': function(){
        jQuery('.external-modal').magnificPopup({
          type: 'iframe'
        });
      },
      'callbackMarkerClick': function(){
        jQuery('.external-modal').magnificPopup({
          type: 'iframe'
        });
      },
      'dataType': 'json',
      'dataLocation': /directory/data/latlong.php'
    });


Could you help please.

**Comment by bjorn2404** [comment]
@julienwangchang Yes, it is a CSS issue and it's because of the global img max-width property:

`img:not(.tribe-events-spinner-medium){
	max-width: 100%;
	height: auto;
}`

Add:

`.bh-sl-container img {
      max-width: none;
}`

**Comment by julienwangchang** [comment]
That's working fine.
Thanks.
