### ISSUE TITLE
JSON file structure

### ISSUE THREAD

**Issue by FBosch91** [bjorn2404/jQuery-Store-Locator-Plugin#75]
Is there any JSON or DB Structure required when i want to use dataType:Json ?
With structure I mean the column names in the DB and the keys in the JSON file.

"lat" and "lng" are static (required) fields ?

**Comment by bjorn2404** [comment]
lat and lng should be the only required fields if I'm recalling correctly. If you have address data you want displayed on the front end that have different column names you'll want to update the Handlebars templates in dist/assets/js/plugins/storeLocator/templates/
