### ISSUE TITLE
autoGeocode on enter input

### ISSUE THREAD

**Issue by degoya** [bjorn2404/jQuery-Store-Locator-Plugin#84]
is it possible to trigger the autoGeocode on enter search input instead of storelocator init?
i'd like to avoid getting the geocode before using the storelocator.

**Comment by bjorn2404** [comment]
That's not currently built into the plugin.

**Comment by bjorn2404** [comment]
@degoya I've added a new geocodeID setting in v2.5.0 that allows you to trigger the HTML geocoding API with a button. I've also moved the HTML geocoding functionality into a new public method called htmlGeocode so you should be able to call it how you want.
