### ISSUE TITLE
Callback after complete load of the location list

### ISSUE THREAD

**Issue by JanSchmidhofer** [bjorn2404/jQuery-Store-Locator-Plugin#85]
Is it possible to run a function after the list with the locations is completely created ? 

I want some jquery events on the list items and i tried to run my code via callbackSuccess. But this doesnt work because the list isnt complete yet. Ive tried it with a setTimeout function to wait for the list, but this is not the best way.

**Comment by bjorn2404** [comment]
Try using the callbackFilters setting. That should fire towards the very end of the process.

**Comment by JanSchmidhofer** [comment]
big thanks !
