### ISSUE TITLE
Map disappears after failed search

### ISSUE THREAD

**Issue by enrmbigg** [bjorn2404/jQuery-Store-Locator-Plugin#88]
So upon a wrong search the map disappears then fails to reappear upon a successful search,
This are the settings am using with the most recent version

     'dataType': 'json',
     'dataRaw': '@Html.Raw(json1.Replace("\r\n", ""))',
         'mapSettings': {
          zoom: 9,
          mapTypeId: google.maps.MapTypeId.ROADMAP
          },
      'maxDistance': true,
      'storeLimit': 600,
      'fullMapStartBlank': 5,
      'slideMap': false,
      'defaultLoc': true,
      'defaultLat': 54.093409,
      'defaultLng': -2.89479

**Comment by bjorn2404** [comment]
You're using v2.3.3? I pushed an update last night that should address this issue.

**Comment by enrmbigg** [comment]
Apologies, am using v2.3.2.
I have updated to v2.3.3 and this is now solved.
