### ISSUE TITLE
Will not zoom in on nearest markers

### ISSUE THREAD

**Issue by isaacdunyo** [bjorn2404/jQuery-Store-Locator-Plugin#89]
I'm trying to use the query string example with store locations in different cities and countries but whenever I run a search, it shows all the markers instead of zooming in on the nearest locations.

Only when I run a search using the form on the results page do I get the right zoom.

Is there a setting I have overlooked for this?

Thanks

**Comment by isaacdunyo** [comment]
Never mind, found a workaround. Great plugin!

**Comment by mvaneijgen** [comment]
@isaacdunyo could you elaborate? I'm looking for this
