### ISSUE TITLE
Search map questions

### ISSUE THREAD

**Issue by derdida** [bjorn2404/jQuery-Store-Locator-Plugin#90]
Hello,

thanks again for sharing this great plugin! I have some questions about using the POI seach feature. At the moment when there is no search result, it shows me a map mittle of the ocean with a marker - can i set the default location here? So when there is no result, it should just show me the parameters of my default location.

Is it possible to implement a server-side search functionality?

Thanks in advance!

**Comment by bjorn2404** [comment]
The no results location is not currently something that can be changed with the settings but you could change the code in the plugin. The coordinates are set in the processData method around line 1848.

For server side searching I'd recommend looking at my blog post on using the plugin with thousands of locations: http://www.bjornblog.com/web/using-the-jquery-store-locator-with-thousands-of-locations
