### ISSUE TITLE
Map Not Loading - 1000 Locations 

### ISSUE THREAD

**Issue by blackhat840** [bjorn2404/jQuery-Store-Locator-Plugin#91]
Hello!  I'm having some trouble with your locator.  None of the examples will load my locations.  I've dumped them into xml, json, kml, and even used the raw data using a query to dump them into the page.  The map does not load and the locations are in the source when I view source on Chrome or any browser.  I'm not sure what I'm doing wrong, is there a limit on how many locations you can have?  Right now I've got my query limiting it to 9 locations out of my 1000.

You can view the page here: http:///locator/rawdata-example.cfm 

the xml and json files are located in the default /data directory for the regular examples. Any help would be greatly appreciated!  You are the only plugin I can find other than wordpress store locators so I would love to get this working.
@bjorn2404

**Comment by blackhat840** [comment]
Well I figured it out, happened to be the data I was pulling had some odd characters that was breaking my json and xml files.

**Comment by bjorn2404** [comment]
Yeah, that will do it. Glad you got it sorted out.
