### ISSUE TITLE
Search on map move

### ISSUE THREAD

**Issue by musdy** [bjorn2404/jQuery-Store-Locator-Plugin#95]
Is there an option to do a search on the visible area on the map? If the user searches and then moves the map, new search results do not appear.

**Comment by bjorn2404** [comment]
Yeah, the visibleMarkersList setting.

**Comment by Spenquatch** [comment]
I have a similar question, I have roughly 4500 store locations. I am initially loading 100 locations. When they drag the map and move the center, I would like for it to load more locations. Is this possible? I found the "on center change" event listener, and that it runs "checkVisibleMarkers". But how can I initialize it to load more from the JSON file based on the new center?

**Comment by musdy** [comment]
+1

**Comment by bjorn2404** [comment]
Ok, triggering a new search based on moving the map currently isn't part of the plugin but I can look into adding it to a future version.

**Comment by bjorn2404** [comment]
@musdy @Spenquatch added new dragSearch setting in v2.5.0.
