### ISSUE TITLE
No results when using browser geo-location with maxDistance =  true

### ISSUE THREAD

**Issue by joesparacio** [bjorn2404/jQuery-Store-Locator-Plugin#98]
We just added a hidden input field with id="bh-sl-maxdistance" and a value of 75. For certain product categories, we are setting maxDistance to "true" to limit the results. This works fine when you manually enter an address, city, state, or ZIP code, but always returns zero results if you let the browser detect your location (see below).

Using browser geo-location:

![screen shot 2016-02-02 at 8 16 19 am](https://cloud.githubusercontent.com/assets/5084198/12755702/5d35c760-c985-11e5-9fda-5a3e12096ab6.png)

Using ZIP code 90040:

![screen shot 2016-02-02 at 8 16 46 am](https://cloud.githubusercontent.com/assets/5084198/12755705/6238f96c-c985-11e5-93e2-5416122c0922.png)

Any thoughts?

**Comment by joesparacio** [comment]
UPDATE: We installed the latest version of Handlebars and your plugin, and we are now getting results when autoGeocode is set to true, but the maxDistance limit is not applied. It looks like you are only checking this value on form submit. Is it possible to initialize the locator with a maxDistance value so it works with autoGeocode?

**Comment by bjorn2404** [comment]
Hi, sorry for the delay. There currently isn't a way to handle that with the plugin.

**Comment by bjorn2404** [comment]
This issue has been addressed in v2.5.3
